var u=[
['մասին','about','mɑˈsin'],
['ըստ','according to',''],
['հետո','after','hɛˈtɔ'],
['էլի','again*',''],
['նորից','again**',''],
['դեմ','against','dɛm'],
['բոլոր','all*','bɔˈlɔɾ'],
['բոլորը','all**','bɔˈlɔɾə'],
['ամբողջ','all around','ɑmˈbɔχʧʰ'],
['արդեն','already','ɑɾˈtʰɛn'],
['նաև','also','nɑˈjɛv'],
['միշտ','always','miʃt'],
['եմ','am','ɛm'],
['դրամ','amd','dəˈɾɑm'],
['և','and*',''],
['իսկ','and**','isk'],
['ու','and***','u'],
['այլ','another','ɑjl'],
['ուրիշ','another*','uˈɾiʃ'],
['որևէ','any','vɔɾɛˈvɛ'],
['են','are**','ɛn'],
['ենք','are*','ɛŋkʰ'],
['հայ','armenian****','hɑj'],
['հայաստանի','armenian*',''],
['հայկական','armenian**','hɑjkɑˈkɑn'],
['հայոց','armenian***','hɑˈjɔʦʰ'],
['որպես','as','vɔɾˈpɛs'],
['ետ','back','jɛt'],
['հիմնական','basic','himnɑˈkɑn'],
['լինի','be it',''],
['որովհետև','because','vɔɾɔfhɛˈtɛv'],
['պատճառով','because of this','pɑtʧɑˈrɔv'],
['եղել','been',''],
['ահա','behold!','ɑˈhɑ'],
['լինելու','being',''],
['բացի','besides','bɑˈʦʰi'],
['միջև','between','miˈʤɛv'],
['բայց','but','bɑjʦʰ'],
['եկավ','came',''],
['կարող','can','kɑˈɾɔʁ'],
['կարելի','can be','kɑɾɛˈli'],
['գլխավոր','chief','ɡəlχɑˈvɔɾ'],
['եկել','to come',''],
['գալիս','coming','ɡɑˈlis'],
['երկրի','country',''],
['օր','day','ɔɾ'],
['տարբեր','different','tɑɾˈbɛɾ'],
['չեն','do not',''],
['չունի','does not have',''],
['անում','doing',''],
['իրար','each other','iˈɾɑɾ'],
['ութ','eight','utʰ'],
['նույնիսկ','even','ˈnujnisk'],
['անգամ','even once','ɑŋˈkʰɑm'],
['ամեն','everything','ɑˈmɛn'],
['առաջին','first','ɑrɑˈʧʰin'],
['հինգ','five','hiŋɡ'],
['համար','for','hɑˈmɑɾ'],
['օրինակ','for example','ɔɾiˈnɑk'],
['առաջ','forward','ɑˈrɑʧʰ'],
['չորս','four','ʧʰɔɾs'],
['ազատ','free','ɑˈzɑt'],
['կողմից','from','kɔʁˈmiʦʰ'],
['տվել','gave*',''],
['տվեց','gave**',''],
['ընդհանուր','general','əntʰhɑˈnuɾ'],
['տալիս','give',''],
['լավ','good','lɑv'],
['մեծ','great','mɛʦ'],
['ունեցել','had',''],
['ձեռք','hands','ʣɛrkʰ'],
['լինում','happens',''],
['ունի','has',''],
['ունեն','have',''],
['ինքը','he himself','ˈiŋkʰə'],
['ծանր','heavy','ˈʦɑnəɾ'],
['իր','her***','iɾ'],
['նրա','her*','nəˈɾɑ'],
['նրան','her**','nəˈɾɑn'],
['այստեղ','here','ɑjsˈtɛʁ'],
['ՀՀ','RA','həˈhə'],
['բարձր','high','ˈbɑɾʦʰəɾ'],
['ինքն','himself','ˈiŋkʰən'],
['տուն','house','tun'],
['ինչպես','how','inʧʰˈpɛs'],
['քանի','how many','kʰɑˈni'],
['որքան','how much','vɔɾˈkʰɑn'],
['սակայն','however','sɑˈkɑjn'],
['մարդու','human',''],
['ես','i am','jɛs'],
['չեմ','i am not',''],
['եթե','if','jɛˈtʰɛ'],
['կարևոր','important','kɑɾɛˈvɔɾ'],
['մեջ','in*','mɛʧʰ'],
['մէջ','in**',''],
['հայաստանում','in armenia',''],
['դեպքում','in case',''],
['որպեսզի','in order','vɔɾˈpɛszi'],
['միջազգային','international','miʤɑzɡɑˈjin'],
['է','is','ɛ'],
['այն','it','ɑjn'],
['կարծես','it looks like',''],
['թվում','it seems','tʰvum'],
['չէր','it was not',''],
['դրա','its',''],
['պես','just like that','pɛs'],
['հենց','just right','hɛnʦʰ'],
['հայտնի','known','hɑjtˈni'],
['վերջին','last','vɛɾˈʧʰin'],
['թող','let','tʰɔʁ'],
['կյանքի','life',''],
['նման','like','nəˈman'],
['քիչ','little','kʰitʃʰ'],
['երկար','long','jɛɾˈkɑɾ'],
['նայում','looking',''],
['տեր','lord','tɛɾ'],
['սիրում','love','siˈɾum'],
['մարդ','man','mɑɾtʰ'],
['ավելի','more','ɑvɛˈli'],
['իմ','my','im'],
['ազգային','national','ɑzɡɑˈjin'],
['մոտ','near','mɔt'],
['պետք','need','pɛtkʰ'],
['անհրաժեշտ','needed','ɑnhəɾɑˈʒɛʃt'],
['նոր','new','nɔɾ'],
['ինը','nine','ˈinə'],
['այլևս','no longer','ɑjˈlɛvs'],
['չի','no*','ʧʰi'],
['չկա','no**',''],
['չէ','no***','ʧʰɛ'],
['ոչ','no****','vɔʧʰ'],
['ոչինչ','nothing','vɔˈʧʰinʧʰ'],
['այժմ','now','ˈɑjʒəm'],
['հիմա','now*','hiˈmɑ'],
['իհարկե','of course','iˈhɑɾkɛ'],
['տարվա','of the year',''],
['որոնց','of which',''],
['հին','old','hin'],
['ին','on*',''],
['վերաբերյալ','on**','vɛɾɑbɛɾˈjɑl'],
['վրա','on it','vəˈɾɑ'],
['մեկ','one*','mɛk'],
['մի','one**','mi'],
['միայն','only','miˈjɑjn'],
['բաց','open','bɑʦʰ'],
['գործում','operate','ɡoɾˈtsum'],
['կամ','or','kɑm'],
['թե','or not','tʰɛ'],
['մեր','ours','mɛɾ'],
['դուրս','out','duɾs'],
['նկատմամբ','over','nəkɑtˈmɑmb'],
['մասը','part',''],
['կուսակցության','party',''],
['ժողովուրդ','people*','ʒɔʁɔˈvuɾtʰ'],
['մարդիկ','people**','mɑɾˈtʰik'],
['մարդկանց','people***','mɑɾtʰˈkɑnʦʰ'],
['տեղ','place','tɛʁ'],
['քաղաքական','political','kʰɑʁɑkʰɑˈkɑn'],
['հնարավոր','possible','hənɑɾɑˈvɔɾ'],
['նախագահ','president','nɑχɑˈɡɑh'],
['հասարակական','public','hɑsɑɾɑkɑˈkɑn'],
['գնում','purchase','ɡəˈnum'],
['հարցը','question',''],
['հանրապետության','republic',''],
['ճիշտ','right','ʧiʃt'],
['ասաց','said',''],
['ասում','say',''],
['երկրորդ','second','jɛɾˈkɾoɾtʰ'],
['տեսնում','see',''],
['յոթ','seven','jɔtʰ'],
['նա','she is','nɑ'],
['պիտի','should','piˈti'],
['ցույց','show','ʦʰujʦʰ'],
['պարզ','simple','pɑɾz'],
['վեց','six','vɛtsʰ'],
['փոքր','small','ˈpʰɔkʰəɾ'],
['այդպես','so*','ɑjdˈpɛs'],
['այնպես','so**','ɑjnˈpɛs'],
['այնքան','so much','ɑjŋˈkʰɑn'],
['ինչ-որ','some',''],
['որոշ','some*',''],
['բան','something','bɑn'],
['սովետական','soviet','sovɛtɑˈkɑn'],
['խոսում','speak',''],
['պետական','state','pɛtɑˈkɑn'],
['դեռ','still','dɛr'],
['այդպիսի','such*','ɑjdpiˈsi'],
['այնպիսի','such**','ɑjnpiˈsi'],
['հանկարծ','suddenly','hɑŋˈkɑɾʦ'],
['տաս','ten','tɑs'],
['քան','than','kʰɑn'],
['այդ','that*','ɑjd'],
['դա','that**','dɑ'],
['որ','that***','vɔɾ'],
['այսինքն','that is to say','ɑjˈsiŋkʰən'],
['մյուս','the other','mjus'],
['նույն','the same','nuɪ̯n'],
['ժամը','the time',''],
['դրանց','their',''],
['դրանք','them*',''],
['նրանց','them**','nəˈɾɑnʦʰ'],
['իրենց','themselves','iˈɾɛnʦʰ'],
['ապա','then*','ɑˈpɑ'],
['ուրեմն','then**','uˈɾɛmən'],
['այնտեղ','there*','ɑjnˈtɛʁ'],
['կա','there**','kɑ'],
['կան','there are','kɑn'],
['նրանք','they are','nəˈɾɑŋkʰ'],
['չէին','they were not',''],
['կարծում','think',''],
['այս','this*','ɑjs'],
['սա','this**','sɑ'],
['այսպես','this way','ɑjsˈpɛs'],
['որոնք','those','vɔˈɾɔŋkʰ'],
['հազար','thousand','hɑˈzɑɾ'],
['երեք','three','jɛˈɾɛkʰ'],
['ժամանակ','time','ʒɑmɑˈnɑk'],
['դեպի','to','dɛˈpi'],
['լինել','to be','liˈnɛl'],
['տալ','to give','tɑl'],
['իրեն','to himself','iˈɾɛn'],
['ինձ','to me','inʣ'],
['ասել','to say','ɑˈsɛl'],
['ում','to whom',''],
['քեզ','to you','kʰɛz'],
['այսօր','today','ɑjˈsɔɾ'],
['ևս','too*',''],
['էլ','too**','ɛl'],
['նույնպես','too***','ˈnujnpɛs'],
['շատ','too****','ʃɑt'],
['քսան','twenty','kʰəˈsɑn'],
['երկու','two','jɛɾˈku'],
['տակ','under','tɑk'],
['մինչև','up*','minˈʧʰɛv'],
['վեր','up**','vɛɾ'],
['մեզ','us','mɛz'],
['ուզում','want',''],
['էի','was*','ɛ(j)i'],
['էր','was**','ɛɾ'],
['մենք','we are','mɛŋkʰ'],
['չենք','we are not',''],
['էինք','we were','ɛ(j)iŋkʰ'],
['թույլ','weak','tʰujl'],
['էին','were','ɛ(j)in'],
['ինչ','what','inʧʰ'],
['երբ','when','jɛɾpʰ'],
['որտեղ','where*','vɔɾˈtɛʁ'],
['ուր','where**','uɾ'],
['որ*','which','vɔɾ'],
['ով','who','ɔv'],
['որի','whose','vɔˈɾi'],
['ինչու','why','inˈʧʰu'],
['կլինի','will be',''],
['հետ','with','hɛt'],
['ընթացքում','within','əntʰɑʦʰˈkʰum'],
['առանց','without','ɑˈrɑnʦʰ'],
['աշխատանքի','work',''],
['աշխարհի','world',''],
['տարի','years','tɑˈɾi'],
['երևան','yerevan',''],
['այո','yes*','ɑˈjo'],
['հա','yes**','hɑ'],
['երեկ','yesterday','jɛˈɾɛk'],
['դու','you*','du'],
['դուք','you**','dukʰ'],
['ձեզ','you***',''],
['եք','you are','ɛkʰ'],
['ձեր','yours*',''],
['քո','yours**','kʰo'],
['զրո','zero','zəˈɾɔ']];

var uu=[
['ազատ մարդ','free man'],
['ազգային հարց','национальный вопрос'],
['ամբողջ օրը','whole day'],
['ամեն անգամ','each time'],
['ամեն բան','everything'],
['ամեն ինչ','everything'],
['ամեն օր','every day'],
['ամենալավ մասը','the best part'],
['այդ գիրքը','that book'],
['այլ ազգերը','another nations'],
['այլևս չկարողացավ','больше не смог'],
['այս անգամ','this time'],
['այս գրքի տերն եմ','I am the owner of this book'],
['այս տարի','this year'],
['այս տունը','this house'],
['այստեղ չի կարելի ծխել','smoking is not allowed here'],
['այսօր զբաղված եմ','I am busy today'],
['աշխատանք անել','to do work'],
['աշխատանքային օր','workday'],
['աշխատանքի ընդունվել','to get a job'],
['աշխատանքի տեղ	place of work'],
['աշխատանքից ուշանալ','to be late from work'],
['աշխարհի ամենամեծ','the largest in the world'],
['աջ, թե՞ ձախ','left or right?'],
['առանց քեզ','without you'],
['առաջ եմ քայլելու','I will walk forward'],
['առաջին մարդ','first man'],
['ասում է, թե պատրաստ է','he says, that he is ready'],
['ավելի մեծ','bigger'],
['ավելի ու ավելի','more and more'],
['բա՞ն ասիր','did you say something?'],
['բարձր շենք','high building'],
['բարձր սար','high mountain'],
['բաց դուռ','open door'],
['գլխավոր անդամներ','main parts'],
['գլխավոր բժիշկ','chief physician'],
['գլխավոր շտաբ','headquarters'],
['գործից հետո','after work'],
['դա ծիծաղելի է','that`s is funny'],
['դեպի հյուսիս','to the north'],
['դեպքը բերել','to happen'],
['դեպքից դեպք','rarely'],
['դեռ պատրաստ չեմ','I am not ready yet'],
['դու իմ ընկերն ես','you are my friend'],
['դու ինձ մի ասա','don`t tell me'],
['դու հայ ես','you is armenian'],
['դուրս գալ','to come out'],
['դուք հայ եք','you are armenians'],
['դուք հայ չեք','you are not armenians'],
['դրա մասին','about that'],
['դրա մասին','about this'],
['դրսից','from the outside'],
['դրսում','in the outside'],
['ե՞րբ ես վերադառնալու','when will you return?'],
['եթե հարցնես','if you ask'],
['ես դեմ եմ','I am against this'],
['ես էլ եմ ուզում','I want too'],
['ես նույնպես','me too'],
['ես ու դու','me and you'],
['ես ունեմ','i have'],
['երեկ տանը չէի','I wasn`t home yesterday'],
['երկար կյանք','long life'],
['երջանիկ կյանք','happy life'],
['էլ չեմ տեսնի քեզ','I won`t see you any more'],
['թող ուտի','let him eat'],
['թույլ տալ','to allow'],
['ժամանակի հարց է','a matter of time'],
['ժամը քանի՞սն է','what time is it?'],
['ինձ համար','for me'],
['ինչ ուզես','whatever you want'],
['ինչ-որ բան','что-то'],
['ինչ-որ մեկը','кто-то'],
['իսկ ինչո՞ւ ոչ','and why not?'],
['լավ գինի','good wine'],
['լավ մարդ է','is a good person'],
['ծանր քար','heavy stone'],
['ծառերի մեջ','among the trees'],
['ծառի տակ','under the tree'],
['կարելի է','it is possible'],
['կարող լինել','to be able to'],
['կարևոր որոշում','important decision'],
['կես ժամ','half an hour'],
['կյանքումս','in all of my life'],
['հա՞յ ես','are you an armenian?'],
['հայկական կոնյակ','armenian brandy'],
['հայոց գրեր','armenian letters'],
['հայոց լեզու','armenian language'],
['հայոց պատմություն','armenian history'],
['հայտնի երգիչ','famous singer'],
['հայտնի չէ','it is not known'],
['հանդիպման ընթացքում','during the meeting'],
['հարց տալ','to ask'],
['հենց հիմա','right now'],
['հետ գնալ','to go back'],
['հետո ուշ կլինի','it will be late then'],
['հերոսի պես','like a hero'],
['հիմարի նման','like an idiot'],
['հիմնական կապիտալ','basic capital'],
['հին խնդիր','old problem'],
['հին վերարկու','old coat'],
['հնարավոր չէ','is not possible'],
['մասերի բաժանել','to divide into pieces'],
['մեծ եղբայր','elder brother'],
['մեծ մատ','thumb'],
['մեծ շուն','big dog'],
['մեծ քար','large stone'],
['մենք իրար սիրում ենք','we love each other'],
['մեջից','from the inside'],
['մի անգամ','once'],
['մի բան անել','to do something'],
['մի բան արա՛','o something!'],
['մի բան ուտել','to eat something'],
['մի կատու տեսա','I saw a certain cat'],
['մի միտք','an idea'],
['մի քիչ','a little'],
['մի օր','once'],
['մի՛ գնա','don`t go!'],
['միայն քեզ եմ սիրում','I love only you'],
['մինչև ցամպս','even to the clouds'],
['մինև ուրանօ՞ր','how far?'],
['միջազգային կազմակերպություն','international organization'],
['մոտդ փող կա՞','do you have any money on you?'],
['մոտս մնա','stay with me'],
['նա ոչինչ չգիտի','he knows nothing'],
['նման մարդիկ','similar people'],
['նոր գիրք','new book'],
['նոր մեքենա','new car'],
['շատ քիչ','too few'],
['ոչ երբեք','never'],
['ոչ մի բան','nothing'],
['ոչ ոք','nobody'],
['որոշ մարդիկ հիմար են','some people are stupid'],
['որտեղի՞ց եք','where are you from?'],
['ուտելու ժամանակ','during eating'],
['ուտելուց առաջ','before eating'],
['պատի դեմ','facing the wall'],
['պետք է գնաս','you need to go'],
['պետք լինել','to be needed'],
['սա իմ տեղն է','this is my place'],
['սեղանի վրա','on the table'],
['վերջին անգամ','last time'],
['վերջին դատաստան','the Last Judgment'],
['վերջին խոսք','the last word'],
['տան մեջ','in the house'],
['տուփի մեջ','in the box'],
['փոքր եղբայր','younger brother'],
['փոքր մեքենա	small car'],
['փոքր շուն	little dog'],
['քաղաքից դուրս','outside the city'],
['քարքարոտ տեղ','rocky locale'],
['քեզ հետ','with you'],
['քեզ նման չեմ','I am not similar to you'],
['քիչ մարդ','few people'],
['քիչ ուտել','to eat a little'],
['օրինակի համար','for example']];


