var u=[
['այդքան','so mach','ɑjtˈkʰɑn'],
['այդքան էլ չէ','not so much','ɑjtˈkʰɑn ‿ ɛl ʧʰɛ'],
['այդքան վաղ','so early','ɑjtˈkʰɑn vɑʁ'],
['անելիք','task','ɑnɛˈlikʰ'],
['անելիքներ','tasks','ɑnɛlikʰˈnɛɾ'],
['անելիքներ ունեմ','ɑnɛlikʰˈnɛɾ ունեմ','ɑnɛlikʰˈnɛɾ uˈnɛm'],
['առավոտ','morning','ɑrɑˈvɔt'],
['առավոտյան','in morning','ɑrɑvɔtˈjɑn'],
['արթնանալ','to wake up','ɑɾtʰnɑˈnɑl'],
['արթնացել','woke up','ɑɾtʰnɑˈʦʰɛl'],
['արթնացնել','to wake','ɑɾtʰnɑˈʦʰnɛl'],
['արթուն','awake','ɑɾˈtʰun'],
['բարի','kind','bɑˈɾi'],
['բարի լույս','good morning','bɑˈɾi lujs'],
['երեք','three','jɛˈɾɛkʰ'],
['էլ','too','ɛl'],
['ինչու','why','inˈʧʰu'],
['լավ','good','lɑv'],
['լավ քնեցիր','you sleep well','lɑv kʰəneˈʦʰiɾ'],
['լույս','light','lujs'],
['հաջող','lucky','hɑˈʤɔʁ'],
['հաջող*','bye-bye','hɑˈʤɔʁ'],
['հաջողություն','success','hɑʤɔʁuˈʦʰjun'],
['հաջողություն քեզ','good luck to you','hɑʤɔʁuˈʦʰjun kʰɛz'],
['շատ','many','ʃɑt'],
['շատ անելիքներ','lots things to do','ʃɑt ɑnɛlikʰˈnɛɾ'],
['շնորհ','grace','ʃənɔɾ'],
['շնորհակալ','thankful','ʃənɔɾɑˈkɑl'],
['շնորհակալություն','thanks','ʃənɔɾɑkɑluˈʦʰjun'],
['ունեմ','I have','uˈnɛm'],
['ունենալ','to have','unɛˈnɑl'],
['ունես','you have','uˈnɛs'],
['ունի','he has','uˈni'],
['չէ','no','ʧʰɛ'],
['վաղ','early','vɑʁ'],
['վաղ առավոտյան','early in the morning','vɑʁ ɑrɑvɔtˈjɑn'],
['վաղ արթնացել','vɑʁ ɑɾtʰnɑˈʦʰɛl','vɑʁ ɑɾtʰnɑˈʦʰɛl'],
['քեզ','to you','kʰɛz'],
['քնել','to sleep','kʰəˈnɛl'],
['քնեցիր','you sleep','kʰəneˈʦʰiɾ']];