var u=[
['Աննա','Anna','ɑˈnːɑ'],
['ինչ ես անում','what are you doing','inʧʰ ‿ ɛs ɑˈnum'],
['Մարկ','Mark','mɑɾk'],
['միացյալ','united','miⱼɑʦʰˈjɑl'],
['Միացյալ Նահանգներ','United States','miⱼɑʦʰˈjɑl nɑhɑŋɡˈnɛɾ'],
['Միացյալ Նահանգներից','from United States','miⱼɑʦʰˈjɑl nɑhɑŋɡnɛɾˈiʦʰ'],
['Մոսկվա','Moscow','mɔskˈvɑ'],
['մոսկվաից','from Moscow','mɔskvɑˈiʦʰ'],
['Նյու Յորք','New York City','nju jɔɾˈkʰiʦʰ'],
['Նյու Յորքից','from New York City','nju jɔɾˈkʰiʦʰ'],
['Ռուսաստան','Russia','rusɑsˈtɑn'],
['Ռուսաստանից','from Russia','rusɑstɑˈniʦʰ'],
['անուն','name','ɑˈnun'],
['անունդ','your name','ɑˈnunət'],
['անունդ ինչ է','what is your name','ɑˈnunətʰ ˈinʧʰ ‿ ɛ'],
['ինչ','what','inʧʰ'],
['ինչու','why','inˈʧʰu'],
['իսկ դու','and you','isk du'],
['իսկ ինչու ոչ','and why not','isk inˈʧʰu vɔʧʰ'],
['իսկ','and','isk'],
['իսկ քոնը','and yours','isk kʰɔnə'],
['ծանոթ','known','ʦɑˈnɔtʰ'],
['ծանոթ դեմք','familiar face','ʦɑˈnɔtʰ dɛmkʰ'],
['ծանոթ*','friend','ʦɑˈnɔtʰ'],
['ծանոթանալ','to get to know','ʦɑnɔtʰɑˈnɑl'],
['ծանոթանալ*','to meet','ʦɑnɔtʰɑˈnɑl'],
['ծանոթություն','introduction','ʦɑnɔtʰuˈʦʰjun'],
['կլոր դեմք','round face','kəˈlɔɾ dɛmkʰ'],
['մահացու մեղքեր','deadly sins','mɑhɑˈʦʰu mɛχˈkʰɛɾ'],
['յոթ','seven','jɔtʰ'],
['յոթ մահացու մեղքեր','seven deadly sins','jɔtʰ mɑhɑˈʦʰu mɛχˈkʰɛɾ'],
['յոթ մեղքեր','seven sins','jɔtʰ mɛχˈkʰɛɾ'],
['նահանգ','state','nɑˈhɑŋɡ'],
['նահանգներ','states','nɑhɑŋɡˈnɛɾ'],
['ոչ','not','vɔʧʰ'],
['որ','which','vɔɾ'],
['որ քաղաքից','from which city','vɔɾ kʰɑʁɑkʰˈiʦʰ'],
['որտեղ','where','vɔɾˈtɛʁ'],
['որտեղից','from where','vɔɾtɛˈʁiʦʰ'],
['որտեղից ես','where are you from','vɔɾtɛˈʁiʦʰ ‿ ɛs'],
['ռուս','Russian','rus'],
['ռուսներ','Russian persons','rusˈnɛɾ'],
['տեղ','place','tɛʁ'],
['քաղաք','city','kʰɑˈʁɑkʰ'],
['քաղաքից','from city','kʰɑʁɑˈkʰiʦʰ'],
['քոնը','yours','kʰɔnə']];