var u=[
['ԱՄՆ','USA','ɑməˈnə'],
['ԱՄՆ-ից','from USA','ɑmˈniʦ'],
['Բլեկ','Black','blɛk'],
['Մարկ','Mark','mɑɾk'],
['Մոսկվա','Moscow','mɔsˈkvɑ'],
['Մոսկվայում','in Moscow','mɔskvɑˈum'],
['ազգ','clan (dated)','ɑzɡ'],
['ազգ','nation','ɑzɡ'],
['ազգանուն','family name','ɑzɡɑˈnun'],
['այժմ','now','ˈɑjʒəm'],
['այժմ որտեղ եք բնակվում','where do you (pl) live now','ˈɑjʒəm vɔɾˈtɛʁ ‿ ɛkʰ bənɑkvˈum'],
['անուն','name','ɑˈnun'],
['բնակել','to settle','bənɑˈkɛl'],
['բնակվել','to live','bənɑkˈvɛl'],
['ժամանել','to arrive','ʒɑmɑˈnɛl'],
['ինչ է','what is','ˈinʧʰ ‿ ɛ'],
['հայր','father','hɑjɾ'],
['հայրանուն','patronymic','hɑjɾɑˈnun'],
['ձեր','of yours (pl)','ʣɛɾ'],
['ձեր անունն ինչ է','what is your (pl) name','ʣɛɾ ɑˈnunːˈinʧʰ ‿ ɛ'],
['որտեղ','where','vɔɾˈtɛʁ'],
['որտեղ եք','where are you (pl)','vɔɾˈtɛʁ ‿ ɛkʰ'],
['որտեղից','from where','vɔɾtɛˈʁiʦʰ'],
['որտեղից եք','where are you (pl) from','vɔɾtɛˈʁiʦʰ ‿ ɛkʰ'],
['ութ','eight','utʰ']];