var u=[
['բաժակ','glass*','bɑˈʒɑk'],
['բարի','goog','bɑˈɾi'],
['բարի օր','good day','bɑˈɾi ɔɾ'],
['բարի*','kind','bɑˈɾi'],
['բուտերբրոդ','sandwich','buterbrot'],
['բուտերբրոդ և սուրճ','sandwich and coffee','buterbrot jɛv suɾʧ'],
['գալ','to come','ɡɑl'],
['գալ*','to arrive','ɡɑl'],
['գավաթ','cup','ɡɑˈvɑtʰ'],
['գավաթ*','glass','ɡɑˈvɑtʰ'],
['գնել','to buy','ɡəˈnɛl'],
['գնում','purchase','ɡəˈnum'],
['ընդմիջման ժամ է','itˈs break time','əndmiʤˈmɑn ˈʒɑm ‿ ɛ'],
['ընդմիջման','of break','əndmiʤˈmɑn'],
['ընդմիջում','break','əndmiˈʤum'],
['ընդմիջում*','interrupt','əndmiˈʤum'],
['ժամ','time','ʒɑm'],
['ժամ*','hour','ʒɑm'],
['իհարկե','sure','iˈhɑɾkɛ'],
['իհարկե*','of couse','iˈhɑɾkɛ'],
['ինչ','what','inʧʰ'],
['ինչ կուտես','what will you eat','inʧʰ kuˈtɛs'],
['կուտես','you will eat','kuˈtɛs'],
['իսկ դու','and you','isk du'],
['խմոր','тесто','χəˈmɔɾ'],
['խմոր*','dough','χəˈmɔɾ'],
['խմորեղեն','pastries','χəˈmɔɾɛʁɛn'],
['խմորեղեն և հյութ','pastries and juice','χəˈmɔɾɛʁɛn jɛv hjutʰ'],
['կարող է','can','kɑˈɾɔʁ ‿ ɛ'],
['կարող է քեզ հետ գալ','can come with you','kɑˈɾɔʁ ‿ ɛ kʰɛz hɛt ɡɑl'],
['հյութ','juice','hjutʰ'],
['մի','a','mi'],
['մի բաժակ հյութ','a glass of juice','mi bɑˈʒɑk hjutʰ'],
['մի բաժակ','a glass','mi bɑˈʒɑk'],
['մի գավաթ սուրճ','a cup of coffee','mi ɡɑˈvɑtʰ suɾʧ'],
['մի գավաթ','a cup','mi ɡɑˈvɑtʰ'],
['մի*','one','mi'],
['մի**','some','mi'],
['ուտել','to eat','uˈtɛl'],
['ուր ես','where are you','ˈuɾ ‿ ɛs'],
['ուր ես գնում','where are you going','ˈuɾ ‿ ɛs ɡəˈnum'],
['չորս','four','ʧʰɔɾs'],
['սուրճ','coffee','suɾʧ'],
['սրճարան','café','səɾʧɑˈɾɑn'],
['քեզ հետ','with you','kʰɛz hɛt'],
['քեզ հետ գալ','come with you','kʰɛz hɛt ɡɑl'],
['և','and','jɛv']];