var u=[
['անդամ','member','ɑnˈtʰɑm'],
['անդամներ','members','ɑntʰɑmˈnɛɾ'],
['բարև','hello','bɑˈɾɛv'],
['բարև ձեզ','hello to you','bɑˈɾɛv ʣɛz'],
['դուք','you (pl)','dukʰ'],
['երկու','two','jɛɾˈku'],
['ընտանիք','family','əntɑˈnikʰ'],
['ընտանիքի անդամ','family member','əntɑniˈkʰi ɑnˈtʰɑm'],
['ընտանիքի անդամներ','members of family','əntɑniˈkʰi ɑntʰɑmˈnɛɾ'],
['ինչ','what','inʧʰ'],
['ինչպես','how','inʧʰˈpɛs'],
['ինչպես են','how are they','inʧʰˈpɛs ‿ ɛn'],
['ինչպես եք','how are you','inʧʰˈpɛs ‿ ɛkʰ'],
['լավ','good','lɑv'],
['լավ է','it`s good','ˈlɑv ‿ ɛ'],
['լավագույն','best','lɑvɑˈɡujn'],
['լավագույն մաղթանքներ','best wishes','lɑvɑˈɡujn mɑχtʰɑŋkʰˈnɛɾ'],
['լավագույն մաղթանքներս','my best wishes','lɑvɑˈɡujn mɑχtʰɑŋkʰˈnɛɾəs'],
['հաղորդել','to transmit','hɑʁɔɾˈtʰɛl'],
['հաղորդել*','to inform','hɑʁɔɾˈtʰɛl'],
['հաղորդեք նրան','let him know','hɑʁɔɾˈtʰɛkʰ nəˈɾɑn'],
['հանդիպել ','to meet','hɑndiˈpɛl'],
['հանդիպում','meeting','hɑndiˈpum'],
['հիանալի','wonderful','hijɑnɑˈli'],
['ձեզ','to you','ʣɛz'],
['ձեզ տեսնել','to see you','ʣɛz tɛsˈnɛl'],
['ձեր կինը','your wife','ʣɛɾ kinə'],
['մաղթանք','wish','mɑχˈtʰɑŋkʰ'],
['մաղթանքներ','wishes','mɑχtʰɑŋkʰˈnɛɾ'],
['մաղթանքներս','my wishes','mɑχtʰɑŋkʰˈnɛɾəs'],
['մինչ','until','minʧʰ'],
['նոր','new','nɔɾ'],
['նույնպես','also','ˈnujnpɛs'],
['նրան','him','nəˈɾɑn'],
['նրան*','her','nəˈɾɑn'],
['շնորհ','grace','ʃənɔɾ'],
['շնորհակալ','grateful','ʃənɔɾɑˈkɑl'],
['շնորհակալ եմ','thank you','ʃənɔɾɑˈkɑl ‿ ɛm'],
['շնորհակալություն','thanks','ʃənɔɾɑkɑluˈʦʰjun'],
['ոնց է','how is it','ˈvɔnʦʰ ‿ ɛ'],
['ուրախ','happy','uˈɾɑχ'],
['ուրախ եմ','I am happy','uˈɾɑχ ‿ ɛm'],
['պես','like','pɛs'],
['տեսնել','to see','tɛsˈnɛl'],
['փոխադարձ','mutual','pʰɔχɑˈdɑɾʦʰ']];