var u=[
['Լոնդոն','London','lɔnˈdɔn'],
['Լոնդոնում','in London','lɔndɔˈnum'],
['Մոսկվա','Moscow','mɔskˈvɑ'],
['Մոսկվայում','in Moscow','mɔskvɑˈum'],
['ազգ','nation','ɑzɡ'],
['ազգություն','nationality','ɑzɡuˈʦʰjun'],
['ապրիլին','in April','ɑpɾiˈlin'],
['ապրիլ','April','ɑpˈɾil'],
['դու','you','du'],
['ես ծնվել եմ','I was born','jɛs ʦənˈvɛl ‿ ɛm'],
['երբ','when','jɛɾpʰ'],
['երբ ես ծնվել','when was you born','ˈjɛɾpʰ ‿ ɛs ʦənˈvɛl'],
['երկու','two','jɛɾˈku'],
['երկու հազար','2000','jɛɾˈku hɑˈzɑɾ'],
['թիվ','number','tʰiv'],
['թվական','date','tʰəvɑˈkɑn'],
['թվական*','year','tʰəvɑˈkɑn'],
['թվական**','Numeral','tʰəvɑˈkɑn'],
['ինը','nine','inə'],
['ինն','nine','inː'],
['իններորդ','ninth','ˈinɛɾɔɾtʰ'],
['իննսունհինգ','95','inːəsunˈhiŋɡ'],
['իննսունհինգ թվականին','95 year','inːəsunˈhiŋɡ tʰəvɑkɑˈnin'],
['ինչ','what','inʧʰ'],
['իսկ','and','isk'],
['ծին','birth','ʦin'],
['ծնել','to give birth','ʦəˈnɛl'],
['ծնունդ','birth','ʦəˈnund'],
['ծնվել','to be born','ʦənˈvɛl'],
['ծնվել եմ','I was born','ʦənˈvɛl ‿ ɛm'],
['հազար','thousand','hɑˈzɑɾ'],
['հազար իննը հարյուր','1900','hɑˈzɑɾ inːə hɑɾˈjuɾ'],
['հազարերորդ','thousandth','hɑˈzɑɾɛɾɔɾtʰ'],
['հայ','Armenian','hɑj'],
['հայ եմ','I am Armenian','ˈhɑj ‿ ɛm'],
['հայր','father','hɑjɾ'],
['հայրս','my father','hɑjɾəs'],
['մայր','mother','mɑjɾ'],
['մայրս','my mother','mɑjɾəs'],
['որ','which','vɔɾ'],
['որտեղ','where','vɔɾˈtɛʁ'],
['որտեղ ես ծնվել','where was you born','vɔɾˈtɛʁ ‿ ɛs ʦənˈvɛl'],
['ուրեմն','therefore','uˈɾɛmən'],
['անգլիացի ես','you are English','ɑŋɡlijɑˈʦʰi ‿ ɛs'],
['անգլիացի','Englishman','ɑŋɡlijɑˈʦʰi'],
['տեղ','place','tɛʁ']];