var u=[
['ամիս','ɑˈmis','month'],
['այդ դեպքում','in that case','ɑjd dɛpˈkʰum'],
['այլ','other','ɑjl'],
['այս դեպքում','in this case','ɑjs dɛpˈkʰum'],
['անծանոթ','unknown','ɑnʦɑnˈɔtʰ'],
['անծանոթին','to stranger','ɑnʦɑnɔtʰˈin'],
['ասել','to say','ɑˈsɛl'],
['արտահայտել','speak up for','ɑɾtɑhɑjˈtɛl'],
['արտահայտություն','phrase','ɑɾtɑhɑjtuˈʦʰjun'],
['բարի երեկո','good evening','bɑˈɾi jɛɾɛˈkɔ'],
['բարի լույս','good morning','bɑˈɾi lujs'],
['բարի օր','good day','bɑˈɾi ɔɾ'],
['գործ','a work','ɡɔɾʦ'],
['գործ*','job','ɡɔɾʦ'],
['գործել','to work','ɡɔɾˈʦɛl'],
['դեպք','event','dɛpkʰ'],
['դեպք*','incident','dɛpkʰ'],
['դեպք**','occurrence','dɛpkʰ'],
['եթե','if','jɛˈtʰɛ'],
['եթե կին','if woman','jɛˈtʰɛ ˈkin'],
['երբ կարելի է','when possible','jɛɾpʰ kɑɾɛˈli ‿ ɛ'],
['ժամ','hour','ʒɑm'],
['ժամ','time','ʒɑm'],
['ինչպես','how','inʧʰˈpɛs'],
['ինչպես ողջունել','how to greet','inʧʰˈpɛs vɔχˈʧʰujn'],
['իսկ','but','isk'],
['իսկ եթե','what if','isk jɛˈtʰɛ'],
['իսկ եթե կին է','if itˈs a woman','isk jɛˈtʰɛ ˈkin ‿ ɛ'],
['ծանոթ','known','ʦɑnˈɔtʰ'],
['կարելի','possible','kɑɾɛˈli'],
['կարելի է','it is possible','kɑɾɛˈli ‿ ɛ'],
['կարելի է ասել','we can say','kɑɾɛˈli ‿ ɛ ɑˈsɛl'],
['կես','half','kɛs'],
['կեսօր','midday','kɛˈsɔɾ'],
['կեսօրից հետո','afternoon','kɛsɔɾˈiʦʰ hɛˈtɔ'],
['կին','woman','kin'],
['կին*','wife','kin'],
['հանդիպել','to meet','hɑndiˈpɛl'],
['հանդիպել ենք','we met','hɑndiˈpɛl ‿ ɛŋkʰ'],
['հավանաբար','probably','hɑvɑnɑˈbɑɾ'],
['հավանել','to agree','hɑvɑˈnɛl'],
['հետո','after','hɛˈtɔ'],
['հետո*','then','hɛˈtɔ'],
['մարդ','human','mɑɾtʰ'],
['մարդ*','adult male','mɑɾtʰ'],
['մարդ**','husband','mɑɾtʰ'],
['յոթից հետո','after seven','jɔtʰˈiʦʰ hɛˈtɔ'],
['նրան','him','nəˈɾɑn'],
['նրան ասա','tell him','nəˈɾɑn ɑˈsɑ'],
['ողջ','whole','vɔχʧʰ'],
['ողջ*','alive','vɔχʧʰ'],
['ողջույն','greeting','vɔχˈʧʰujn'],
['ողջույն*','hello','vɔχˈʧʰujn'],
['ողջունել','to greet','vɔχʧʰuˈnɛl'],
['ողջունել անծանոթին','to greet stranger','vɔχˈʧʰujn ɑnʦɑnɔtʰˈin'],
['ոչ','not','vɔʧʰ'],
['պարոն','sir','pɑˈɾɔn'],
['վեց','six','vɛʦʰ'],
['վեց ամիս','vɛʦʰ ɑˈmis','six months'],
['տասից հետո','after ten','tɑsˈiʦʰ hɛˈtɔ'],
['տասնյոթից հետո','after seventeen','tɑsnjɔtʰˈiʦʰ hɛˈtɔ'],
['տիկին','madam','tiˈkin'],
['տղա','boy','təˈʁɑ'],
['տղա*','son','təˈʁɑ'],
['տղամարդ','man','təʁɑˈmɑɾtʰ'],
['օգուտ','a use','ɔˈkʰut'],
['օգտագործել','to use','ɔkʰtɑɡɔɾˈʦɛl'],
['օգտագործիր','use!','ɔkʰtɑɡɔɾˈʦiɾ'],
['օր','day','ɔɾ']];