var u=[
['ամեն օր','every day','ɑˈmɛn ɔɾ'],
['անց','after','ɑnʦʰ'],
['անց*','past','ɑnʦʰ'],
['անցավ','passed','ɑnʦʰˈɑv'],
['անցնել','to pass','ɑnʦʰˈnɛl'],
['առանձին','apart','ɑrɑnˈʣin'],
['առանձին*','unique','ɑrɑnˈʣin'],
['առանձնապես','special','ɑrɑnʣnɑˈpɛs'],
['առանձնապես բան չկա','nothing special','ɑrɑnʣnɑˈpɛs bɑn ʧʰəˈkɑ'],
['բան չկա','nothing','bɑn ʧʰəˈkɑ'],
['բան','thing','bɑn'],
['բան*','busines','bɑn'],
['բան**','penis','bɑn'],
['բարի','good','bɑˈɾi'],
['բարի գիշեր','good night','bɑˈɾi ɡiˈʃɛɾ'],
['բարի երեկո','good evening','bɑˈɾi jɛɾɛˈkɔ'],
['գիշեր','night','ɡiˈʃɛɾ'],
['գնա','go!','ɡəˈnɑ'],
['գնալ','to go','ɡəˈnɑl'],
['երեկո','evening','jɛɾɛˈkɔ'],
['ինչպես','how','inʧʰˈpɛs'],
['ինչպես անցավ','how did it go','inʧʰˈpɛs ɑnʦʰˈɑv'],
['լավ','OK','lɑv'],
['կա','there is','kɑ'],
['կամ','I am','kɑm'],
['կաս','you is','kɑs'],
['հինգ','five','hiŋɡ'],
['հինգ տարի անց','five years later','hiŋɡ tɑˈɾi ɑnʦʰ'],
['չորս րոպե անց','four minutes later','ʧʰɔɾs ɾɔˈpɛ ɑnʦʰ'],
['հոգնած','tired','hɔkʰˈnɑʦ'],
['հոգնել','become tired','hɔkʰˈnɛl'],
['նորություն','news','nɔɾuˈʦʰjun'],
['նորություն կա','there is news','nɔɾuˈʦʰjun kɑ'],
['նորություն*','newness','nɔɾuˈʦʰjun'],
['ուզել','to want','uˈzɛl'],
['ուզում եմ','I want','uˈzum ‿ ɛm'],
['չկա','there is none','ʧʰəˈkɑ'],
['չկամ','I am not','ʧʰəˈkɑm'],
['չկաս','you is not','ʧʰəˈkɑs'],
['պառկել','to lie','pɑrˈkɛl'],
['պառկիր','lie down!','pɑrˈkiɾ'],
['քնել','to sleep','kʰəˈnɛl'],
['օր','day','ɔɾ'],
['օրդ','your day','ɔɾət']];