var u=[
['այդ','that','ɑjd'],
['այդ*','that which near you','ɑjd'],
['ավարտ','finish','ɑˈvɑɾt'],
['ավարտել','to finish','ɑvɑɾˈtɛl'],
['գիտեմ','I know','ɡiˈtɛm'],
['գիտենալ','to know*','ɡitɛˈnɑl'],
['գիտես','you know','ɡiˈtɛs'],
['գիտի','he know','ɡiˈti'],
['դիզայներ','designer','dizɑjˈnɛɾ'],
['ընտրել','to choose','əntˈɾɛl'],
['թե','or','tʰɛ'],
['թե*','that*','tʰɛ'],
['իմանալ','to know','imɑˈnɑl'],
['ինչ','what','inʧʰ'],
['ինչու ես','why you','inˈʧʰu ‿ ɛs'],
['կրթել','to educate','kəɾˈtʰɛl'],
['կրթություն','education','kəɾtʰuˈʦʰjun'],
['համալսարան','university','hɑmɑlsɑˈɾɑnə'],
['հասակ','age','hɑˈsɑk'],
['հասակ*','height','hɑˈsɑk'],
['հասակից','since','mɑˈnuk hɑsɑˈkiʦʰ'],
['հետ','with','hɛt'],
['մանուկ','child','mɑˈnuk'],
['մանուկ հասակից','since childhood','mɑˈnuk hɑsɑˈkiʦʰ'],
['մաս','part','mɑs'],
['մասնագետ','expert','mɑsnɑˈɡɛt'],
['մասնագիտություն','profession','mɑsnɑɡituˈʦʰjunə'],
['նկարել','to draw','nəkɑˈɾɛl'],
['նկարել*','to photograph','nəkɑˈɾɛl'],
['որ','which','vɔɾ'],
['որն է','what is','vɔɾn ‿ ɛ'],
['որովհետև','because','vɔɾɔfhɛˈtɛv'],
['ունես','you have','uˈnɛs'],
['ուշ','later','uʃ'],
['սիրել','to like','siˈɾɛl'],
['սիրել*','to love','siˈɾɛl'],
['վաղ','early','vɑʁ'],
['վաղ թե ուշ','sooner or later','vɑʁ tʰɛ uʃ'],
['վաղուց','how long','vɑˈʁuʦʰ'],
['տասնչորս','fourteen','tɑsnəˈʧʰɔɾs'],
['քո','your','kʰɔ']];