var u=[
['ամուսնուդ','your husband','ɑmusˈnutʰ'],
['ամուսին','husband','ɑmuˈsin'],
['անուն','name','ɑˈnun'],
['աշխատել','to work','ɑʃχɑˈtel'],
['երեխա','child','jɛɾɛˈχɑ'],
['զբաղվել','be busy with','zbɑʁˈvel'],
['ինչով է զբաղվում','what is he doing','inˈʧʰɔv ‿ ɛ zbɑʁˈvum'],
['ինչու','why','inˈʧʰu'],
['իրավ','true','iˈɾɑv'],
['իրավաբան','lawyer','iɾɑvɑˈbɑn'],
['իրավունք','right','iɾɑˈvuŋkʰ'],
['կին','woman','kin'],
['կին*','wife','kin'],
['կնոջ','wifeˈs','knɔʧʰ'],
['մարդու իրավունքներ','human rights','mɑɾtʰu iɾɑˈvuŋkʰnɛɾ'],
['շնորհավորել','to congratulate','ʃnoɾɑvoˈɾel'],
['շնորհավորում','congratulations','ʃnɔɾɑvɔˈɾum'],
['ունենալ','to have','uneˈnɑl'],
['ունեցել','had','unɛˈʦʰɛl'],
['տասնինը','nineteen','tɑsˈninə'],
['տնտեսագետ','economist','təntɛsɑˈɡɛt'],
['տնտեսություն','economy','təntɛsuʦʰjun']];