var u=[
['աղջիկներ են','they are girls','ɑχt͡ʃʰikˈnɛɾ ɛn'],
['ամուսին','husband','ɑmuˈsin'],
['ամուսնալուծել','to divorce','ɑmusnɑluˈt͡sɛl'],
['ամուսնալուծություն','divorce*','ɑmusnɑlut͡suˈt͡sʰjun'],
['ամուսնալուծված','divorced','ɑmusnɑlut͡sˈvɑt͡s'],
['ամուսնանալ','to marry','ɑmusnɑˈnɑl'],
['ամուսնացած','married','ɑmusnɑˈt͡sʰɑt͡s'],
['ամուսնացած եղել է','he was married','ɑmusnɑˈt͡sʰɑt͡s jɛˈʁɛl ɛ'],
['ամուսնացած եմ','I am married','ɑmusnɑˈt͡sʰɑt͡s ɛm'],
['ամուսնացած ես','you are married','ɑmusnɑˈt͡sʰɑt͡s ɛs'],
['ամուսնացած է','he is married','ɑmusnɑˈt͡sʰɑt͡s ɛ'],
['ամուսնացել','got married','ɑmusnɑˈt͡sʰl'],
['ամուսնացել եմ','I got married','ɑmusnɑˈt͡sʰɛl ɛm'],
['ամուսնու','husbandˈs','ɑmusˈnu'],
['ամուսնուդ անունն','your husbandˈs name','ɑmusˈnutʰ ɑˈnunː'],
['ամուսնություն','marriage','ʃɑt ɑmusnut͡sʰˈjun'],
['ամուրի','unmarried','ɑmuˈɾi'],
['ամուրի եմ','I am single','ɑmuˈɾi ɛm'],
['անգլերենի ուսուցչուհի','English teacher','ɑŋɡlɛɾɛˈni usut͡sʰt͡ʃʰuˈhi'],
['անկեղծ ասաց','honestly said','ɑŋˈkɛχt͡s ɑˈsɑt͡sʰ'],
['ապրել','to live','ɑpˈɾɛl'],
['ապրում եք','you live','ɑpˈɾum ɛkʰ'],
['աջ թե ձախ','left or right','ɑt͡ʃʰ tʰɛ d͡zɑχ'],
['առանձին','apart','ɑrɑnˈd͡zin'],
['առաջ','before','ɑˈrɑt͡ʃʰ'],
['առաջ եմ քայլելու','I will walk forward','ɑˈrɑt͡ʃʰ ɛm kʰɑjlɛˈlu'],
['առաջ*','forward','ɑˈrɑt͡ʃʰ'],
['ասում է, թե պատրաստ է','he says, that he is ready','ɑˈsum ɛ tʰɛ pɑtˈɾɑst ɛ'],
['ավագ եղբայր','older brother','ɑˈvɑkʰ jɛχˈpɑjɾ'],
['ավարտվել բաժանությամբ','end in divorce','ɑvɑɾtˈvɛլ bɑʒɑnut͡sʰˈjamb'],
['բաժանել','to divide','bɑʒɑˈnɛl'],
['բաժանություն','divorce','bɑʒɑnuˈt͡sʰjun'],
['գիշերը','at night','ɡiˈʃɛɾə'],
['գնաց թե','did he go','gənɑt͡sʰ tʰɛ'],
['դայակ ունեք','do you have a babysitter','dɑˈjɑk uˈnɛkʰ'],
['դաս','class','dɑs'],
['դասավանդել','to teach','dɑsɑvɑnˈdɛl'],
['դուք ունեք','you (pl) have','dukʰ uˈnɛkʰ'],
['եղբայրդ','your brother','jɛχˈpɑjɾətʰ'],
['եղել եմ','I have been','jɛˈʁɛl ɛm'],
['եղել ես','you have been','jɛˈʁɛl ɛs'],
['եղել է','he have been','jɛˈʁɛl ɛ'],
['երաժիշտ','musician','jɛɾɑˈʒiʃt'],
['երեխա','child','jɛɾɛˈχɑ'],
['երեխաներ ունես','do you have children','jɛɾɛχɑˈnɛɾ uˈnɛs'],
['երկու երեխա','two children','jɛɾˈku jɛɾɛˈχɑ'],
['զբաղվել','be occupied with','zbɑʁˈvɛl'],
['ընտանիք','family','əntɑˈnikʰ'],
['ընտանիք ունեմ','I have family','əntɑˈnikʰ uˈnɛm'],
['ընտանիք ունեք','you have family','əntɑˈnikʰ uˈnɛkʰ'],
['ինչով է','with what','int͡ʃʰɔv ɛ'],
['ինչով է զբաղվում','what does he do','inˈt͡ʃʰɔv ɛ zbɑʁˈvum'],
['ինչու','why','inˈt͡ʃʰu'],
['իսկ մայրը','and the mother','isk mɑjɾə'],
['իրավաբան','lawyer','iɾɑvɑˈbɑn'],
['իրավաբան է','he is a lawyer','nɑ iɾɑvɑˈbɑn ɛ'],
['լավ գինի','good wine','lɑv giˈni'],
['լավ եք քնում','are you sleeping well','lɑv ɛkʰ kʰəˈnum'],
['լավ ընտանիք է','it is  a good family','lɑv əntɑˈnikʰ ɛ'],
['լուծել','to solve','luˈt͡sɛl'],
['խնամել','to care for','χənɑˈmɛl'],
['ծնող','parent','t͡səˈnɔʁ'],
['ծնողների հետ','with parents','t͡sənɔʁnɛˈɾi hɛt'],
['կարողանալ','to be able to','kɑɾɔʁɑˈnɑl'],
['կարողանալ*','to know how to','kɑɾɔʁɑˈnɑl'],
['կարողանում ենք','we can','kɑɾɔʁɑˈnum ɛŋkʰ'],
['կերակրել','to feed','kɛɾɑkɾəˈɾɛl'],
['կին','woman','kin'],
['կին*','wife','kin'],
['կինս ու ես','my wife and I','kinəs u jɛs'],
['կրտսեր քույր','younger sister','kəɾtˈsɛɾ kʰujɾ'],
['հաճախ','frequently','hɑˈt͡ʃɑχ'],
['հաճախ արթնանալ','wake up often','hɑˈt͡ʃɑχ ɑɾtʰnɑˈnɑl'],
['հիմա չի աշխատում','now he is not working','hiˈmɑ t͡ʃʰi ɑʃχɑˈtum'],
['հինգ','five','hiŋɡ'],
['հինգ տարի առաջ','five years ago','hiŋɡ tɑˈɾi ɑˈrɑt͡ʃʰ'],
['հոգ','care','hɔkʰ'],
['հոգ տանել','to take care','hɔkʰ tɑˈnɛl'],
['ձեր','your','d͡zɛɾ'],
['ձեր հայրը','your father','d͡zɛɾ hɑjɾə'],
['ձեր նորածնին','your newborn','d͡zɛɾ nɔɾɑt͡sənˈin'],
['մեծ ընտանիք','big family','mɛt͡s əntɑˈnikʰ'],
['մեծ տղա','big boy','mɛt͡s təˈʁɑ'],
['մեկ տղա և մեկ աղջիկ','one boy and one girl','mɛk təˈʁɑ jɛv mɛk ɑχˈt͡ʃʰik'],
['մենք ունենք','we have','mɛŋkʰ uˈnɛnkʰ'],
['մեր օրերում','nowadays','mɛɾ ɔɾɛˈɾum'],
['մի քանի անգամ','several times','mi kɑˈni ɑŋˈkʰɑm'],
['նոր ենք երեխա ունեցել','we just had a baby','nɔɾ ɛŋkʰ jɛɾɛˈχɑ unɛˈt͡sʰɛl'],
['նորածնի','newborn','nɔɾɑt͡səˈni'],
['նույնպես','also','ˈnujnpɛs'],
['նույնպես ուզում եմ','I also want','ˈnujnpɛs uˈzum ɛm'],
['նրանց','them','nəˈɾɑnt͡sʰ'],
['նրանցից','from them','nəɾɑnˈt͡sʰit͡s'],
['նրանցից առանձին','separately from them','nəɾɑnˈt͡sʰit͡s ɑrɑnˈd͡zin'],
['նրանք ունեն','they have','nəˈɾɑŋkʰ uˈnɛn'],
['շատ ամուսնություններ','many marriages','ʃɑt ɑmusnut͡sʰjuˈnːɛɾ'],
['շնորհավոր','congratulations','ʃnɔɾɑˈvɔɾ'],
['շնորհավորել','to congratulate','ʃnɔɾɑvɔˈɾɛl'],
['շնորհավորում եմ','congratulations*','ʃnɔɾɑvɔˈɾum  ɛm'],
['ով է խնամում','who takes care','ɔv ɛ χənɑˈmum'],
['որքան','how much','vɔɾˈkʰɑn'],
['որքան հաճախ','how often','vɔɾˈkʰɑn hɑˈt͡ʃɑχ'],
['ուզել','to want','uˈzɛl'],
['ուզում եմ','I want','uˈzum ɛm'],
['ուզում եմ դասավանդել','I want to teach','uˈzum ɛm dɑsɑvɑnˈdɛl'],
['ունեցել եմ','I had','unɛˈt͡sʰɛl ɛm'],
['ուսուցիչ','teacher','usuˈt͡sʰit͡ʃʰ'],
['ուսուցչուհի','female teacher','usut͡sʰt͡ʃʰuˈhi'],
['ուտել','to eat','uˈtɛl'],
['ուտելուց առաջ','before eating','utɛlˈit͡sʰ ɑ'rɑt͡ʃ'],
['սիրուն աղջիկ','pretty girl','siˈɾun ɑχˈt͡ʃʰik'],
['ստիպված ենք','we forced to','stipˈvɑt͡sʰ ɛŋkʰ'],
['ստիպվել','to be forced to','stipˈvɛl'],
['տասնինը','nineteen','tɑsˈninə'],
['տասնյոթ','seventeen','tɑsnəˈjɔtʰ'],
['տասնութ','eighteen','tɑsˈnutʰ'],
['տղա','boy','təˈʁɑ'],
['տղա է, թե աղջիկ','is he boy or girl','təˈʁɑ ɛ tʰɛ ɑˈχt͡ʃʰik'],
['տղաներ են','they are boys','təʁɑˈnɛɾ ɛn'],
['տղաներ են, թե աղջիկներ','are they boys or girls','təʁɑˈnɛɾ ɛn tʰɛ ɑχt͡ʃʰikˈnɛɾ'],
['տնտեսություն','economy','təntɛsuˈt͡sʰjun'],
['քանի տարեկան','how old','kɑˈni tɑrɛˈkɑn'],
['քնել','to sleep','kʰəˈnɛl'],
['քո կնոջ','your wife','mkʰɔ knɔt͡ʃʰ'],
['քույր ու եղբայր','sister and brother','kʰujɾ u jɛχˈpɑjɾ'],
['քույրեր ու եղբայրներ','sisters and brothers','kʰujˈɾɛɾ u jɛχpɑjɾˈnɛɾ'],
['քուն','sleep','kʰun'],
['քսան','twenty','kʰəˈsɑn'],
['քսանմեկ','twenty one','kʰəsɑnˈmɛk'],
['օրը','per a day','ɔɾə']];