var u=[
['ամիս','month','ɑˈmis'],
['արդեն','already','ɑɾˈtʰɛn'],
['երկու','two','jɛɾˈku'],
['երևում',' appearance','jɛɾɛˈvum'],
['լինել','to be','liˈnɛl'],
['կլրանամ','I will be','kəlɾɑˈnɑm'],
['մեծ եմ','I am big','mɛʦ ‿ ɛm'],
['շուտով','soon','ʃuˈtɔv'],
['ութ','eight','utʰ'],
['ուրեմն',' therefore','uˈɾɛmən'],
['չի կարող','you can not ','ʧʰi ‿ kɑˈɾɔʁ'],
['չի կարող պատահել','canˈt happen','ʧʰi ‿ kɑˈɾɔʁ pɑtɑˈhɛl'],
['պատահել','to happen','pɑtɑˈhɛl'],
['տասն','ten','tɑsn'],
['տասներկու','twelve','tɑsnɛɾˈku'],
['տասներկու ամիս','twelve months','tɑsnɛɾˈku ɑˈmis'],
['տասնութ','eighteen','tɑsnəˈutʰ'],
['տարեկան','year old','tɑɾɛˈkɑn'],
['տարեկան*','annual','tɑɾɛˈkɑn'],
['տարի','year','tɑˈɾi'],
['փոքր','small','ˈpʰɔkʰəɾ'],
['փոքր ես երևում','you look small','ˈpʰɔkʰəɾ ‿ ɛs jɛɾɛˈvum'],
['քանի','how many','kʰɑˈni'],
['քանի տարով','for how many years','kʰɑˈni tɑˈɾov'],
['քեզնից','than you','kʰɛzˈniʦʰ'],
['քսանյոթ','27','kʰəsɑnˈjɔtʰ'],
['քսանվեց','26','kʰəsɑnˈvɛʦʰ']];