var u=[
['ես նույնպես լավ եմ','I am fine too','jɛs ˈnujnpɛs lɑv ɛm'],
['հոգնած եմ','I am tired','ɑˈjɔ hɔkʰˈnɑt͡s ɛm'],
['շատ անելիքներ ունեմ','I have a lot to do','ʃɑt ɑnɛˈlikʰnɛɾ uˈnɛm'],
['անելիքներ ունեմ','I have things to do','ɑnɛˈlikʰnɛɾ uˈnɛm'],
['ուզում եմ','I want','uˈzum ɛm'],
['ուզում եմ քնել','I want to sleep','uˈzum ɛm kʰəˈnɛl'],
['ժամը 17-ից հետո','after 5pm','ʒɑmə tɑsnəjɔtʰˈit͡sʰ hɛˈtɔ'],
['17-ից հետո','after 5pm*','tɑsnəjɔtʰˈit͡sʰ hɛˈtɔ'],
['կեսօրից հետո','afternoon','kɛsɔɾˈit͡sʰ hɛˈtɔ'],
['այլ ոչ թե','and not that','ɑjl vɔt͡ʃʰ tʰɛ'],
['դեպք','case','dɛpˈkʰum'],
['զրույց','conversation','zəˈɾujt͡sʰ'],
['զրույց առաջին','conversation first','zəˈɾujt͡sʰ ɑrɑˈt͡ʃʰin'],
['զրույց երկու','conversation second','zəˈɾujt͡sʰ jɛɾˈku'],
['զրույց երեք','conversation three','zəˈɾujt͡sʰ jɛˈɾɛkʰ'],
['լավ քնեցի՞ր','did you sleep well','lɑv kʰəˈnt͡sʰiɾ'],
['վաղ','early','vɑʁ'],
['գերազանց','excellent','ɡɛɾɑˈzɑnt͡sʰ. du'],
['ընտանիք','family','əntɑnˈikʰi'],
['ընտանիքի անդամներ','family members','əntɑnikʰˈi ɑntʰɑmˈnɛɾ'],
['առաջին','first','zəˈɾujt͡sʰ ɑrɑˈt͡ʃʰin'],
['հինգ','five','hiŋɡ'],
['առայժմ*','for now','ɑˈrɑjʒəm'],
['հաղորդեք նրան','give him','hɑʁɔɾˈtʰɛkʰ nəˈɾɑn'],
['ուրախ եմ լսել','glad to hear','uˈɾɑχ ɛm ləˈsɛl'],
['ուրախ եմ տեսնել','glad to see','uˈɾɑχ ɛm tɛsˈnɛl'],
['գնա','go','ɡəˈnɑ'],
['գնա պառկի՛ր','go lie down','ɡəˈnɑ pɑrˈkiɾ'],
['լավ','good','lɑv'],
['առայժմ','good bye!','ɑˈrɑjʒəm'],
['բարի օր','good day','bɑˈɾi ɔɾ'],
['բարի երեկո','good evening','bɑˈɾi jɛɾɛˈkɔ'],
['հաջողություն քեզ','good luck to you','hɑd͡ʒɔʁuˈt͡sʰjun kʰɛz'],
['բարի լույս','good morning','bɑˈɾi lujs'],
['բարի լույս, տիկին','good morning madam','bɑˈɾi lujs tiˈkin'],
['բարի լույս, պարոն','good morning sir','bɑˈɾi lujs pɑˈɾɔn'],
['բարի գիշեր','good night','bɑˈɾi ɡiˈʃɛɾ'],
['հաջող','goodbye','hɑˈd͡ʒɔʁ'],
['բարև','greeting','bɑˈɾɛv'],
['ողջույն','greeting*','vɔχˈt͡ʃʰujn'],
['ուրախ','happy','uˈɾɑχ ɛm'],
['բարև ձեզ','hello to you','bɑˈɾɛv d͡zɛz'],
['ինչպես','how','int͡ʃʰˈpɛs'],
['ինչպես են','how are they','int͡ʃʰˈpɛs ɛn'],
['դուք ինչպես եք','how are you','dukʰ int͡ʃʰˈpɛs ɛkʰ</p>'],
['ինչպես եք','how are you*','int͡ʃʰˈpɛs ɛkʰ'],
['ոնց ես','how are you**','vɔnt͡sʰ ɛs'],
['ինչպես անցավ','how did it go','int͡ʃʰˈpɛs ɑnt͡sʰˈɑv'],
['ինչպես ողջունել','how to greet','int͡ʃʰˈpɛs vɔχt͡ʃʰuˈnɛl'],
['ինչպես ողջունել անծանոթին','how to greet a stranger','int͡ʃʰˈpɛs vɔχt͡ʃʰuˈnɛl ɑnt͡sɑnɔtʰˈin'],
['ինչպես անցավ օրդ','how was your day','int͡ʃʰˈpɛs ɑnt͡sʰˈɑv ɔɾət'],
['իսկ եթե կին է','if it is a woman','isk jɛˈtʰɛ kin ɛ'],
['այդ դեպքում','in that case','ɑjd dɛpˈkʰum'],
['նորություն կա՞','is there news','nɔɾuˈt͡sʰjun kɑ'],
['փոխադարձ','mutual','pʰɔχɑˈdɑɾt͡sʰ'],
['լավագույն մաղթանքներս','my best wishes','lɑvɑˈɡujn mɑχtʰɑŋkʰˈnɛɾs'],
['նոր հանդիպում','new meeting','nɔɾ hɑndiˈpum'],
['այդքան էլ չէ','not so much','ɑjtkʰɑn ɛl t͡ʃʰɛ'],
['առանձնապես բան չկա','nothing special','ɑrɑnd͡znɑpɛs bɑn t͡ʃʰəˈkɑ'],
['արտահայտություն','phrase','ɑɾtɑhɑjtuˈt͡sʰjun'],
['հավանաբար','probably','hɑvɑnɑˈbɑɾ'],
['հավանաբար ժամը 17-ից հետո','probably after 5pm','hɑvɑnɑˈbɑɾ ʒɑmə tɑsnəjɔtʰˈit͡sʰ hɛˈtɔ'],
['այլ ոչ թե տղամարդ','rather than a man','ɑjl vɔt͡ʃʰ tʰɛ təʁɑˈmɑɾtʰ'],
['երկու','second','jɛɾˈku'],
['մինչ նոր հանդիպում','see you soon','mint͡ʃʰ nɔɾ hɑndiˈpum'],
['վեց','six','vɛt͡sʰ'],
['նրան ասա','tell him','nəˈɾɑn ɑˈsɑ'],
['շնորհակալություն','thanks','ʃənɔɾɑkɑluˈt͡sʰjun'],
['այդ դեպքում ասա','then say','ɑjd dɛpˈkʰum ɑˈsɑ'],
['նորություն կա','there is news','nɔɾuˈt͡sʰjun kɑ'],
['բան չկա','there is nothing','bɑn t͡ʃʰəˈkɑ'],
['անելիքներ','things to do','ɑnɛˈlikʰnɛɾ'],
['անծանոթին','to a stranger','ɑnt͡sɑnɔtʰˈin'],
['ողջունել','to greet','vɔχt͡ʃʰuˈnɛl'],
['ողջունել անծանոթին','to greet a stranger','vɔχt͡ʃʰuˈnɛl ɑnt͡sɑnɔtʰˈin'],
['տեսնել','to see','tɛsˈnɛl'],
['օգտագործել','to use','ɔkʰtɑɡɔɾˈt͡sɛl'],
['նույնպես','too','ˈnujnpɛs'],
['օգտագործիր արտահայտությունը','use the phrase','ɔkʰtɑɡɔɾˈt͡siɾ ɑɾtɑhɑjtuˈt͡sʰjunə'],
['օգտագործիր «բարի օր» արտահայտությունը','use the phrase «good day»','ɔkʰtɑɡɔɾˈt͡siɾ bɑˈɾi ɔɾ ɑɾtɑhɑjtuˈt͡sʰjunə'],
['մենք հանդիպել ենք','we have met','mɛŋkʰ hɑndiˈpɛl ɛŋkʰ'],
['իսկ եթե','what if','isk jɛˈtʰɛ'],
['իսկ եթե մենք հանդիպել ենք կեսօրից հետո՞','what if we met in the afternoon?','isk jɛˈtʰɛ mɛŋkʰ hɑndiˈpɛl ɛŋkʰ kɛsɔɾˈit͡sʰ hɛˈtɔ'],
['երբ կարելի է ասել','when can you tell','jɛɾpʰ kɑɾɛˈli ɛ ɑˈsɛl'],
['երբ կարելի է','when possible','jɛɾpʰ kɑɾɛˈli ɛ'],
['երբ կարելի է ասել «բարի երեկո»','when to say «good evening»','jɛɾpʰ kɑɾɛˈli ɛ ɑˈsɛl bɑˈɾi jɛɾɛˈkɔ'],
['մինչ','while','mint͡ʃʰ'],
['ինչու ես այդքան վաղ արթնացել','why are you up so early?','inˈt͡ʃʰu ɛs ɑjtkʰɑn vɑʁ ɑɾtʰnɑˈt͡sʰɛl'],
['վաղ արթնացել','woke up early','vɑʁ ɑɾtʰnɑˈt͡sʰɛl'],
['այդքան վաղ արթնացել','woke up so early','ɑjtkʰɑn vɑʁ ɑɾtʰnɑˈt͡sʰɛl'],
['հիանալի','wonderful','hijɑnɑˈli'],
['այո','yes','ɑˈjɔ'],
['դու','you','du'],
['հոգնած ես','you are tired','hɔkʰˈnɑt͡s ɛs'],
['օրդ','your day','ɔɾət'],
['ձեր կինը','your wife','d͡zɛɾ kinə'],
['զրույց անել','to talk','zəˈɾujt͡sʰ ɑnɛl']];
