var u=[
['Ռուսաստան','Russia','rusɑsˈtɑn'],
['Ռուսաստանի','of Russia','rusɑstɑˈni'],
['Սանկտ Պետերբուրգ','Saint Petersburg','sɑŋkt pɛtɛɾˈbuɾg'],
['ամսաթիվը','date','ɑmsɑˈtʰivə'],
['ասել','to say','ɑˈsɛl'],
['ասեք','say! (pl)','ɑˈsɛkʰ'],
['բարձր խոսել','to speak loudly','ˈbɑɾʦʰəɾ χɔˈsɛl'],
['բնակիչ','resident','bənɑˈkiʧʰ'],
['բնակչության','of resident','bənɑkʧʰuˈʦʰjɑn'],
['բնակչության հասցեն','residential address ','bənɑkʧʰuˈʦʰjɑn hɑsˈʦʰɛn'],
['երկիր','country','jɛɾˈkiɾ'],
['երկրի','of country','jɛɾˈkɾi'],
['թիվ','number','tʰiv'],
['թվական','date','tʰəvɑˈkɑn'],
['թվական*','year','tʰəvɑˈkɑn'],
['թվականի','of date','tʰəvɑkɑˈni'],
['խնդրել','to ask','χəntʰˈɾɛl'],
['խնդրում եմ','please','χəntʰˈɾum ‿ ɛm'],
['խոսել','to speak','χɔˈsɛl'],
['ծննդավայր','birthplace','ʦənəndɑˈvɑjɾ'],
['ծննդյան ամսաթիվը','birthdate','ʦənənˈdjɑn ɑmsɑˈtʰivə'],
['ծննդյան օրը','birthday','ʦənənˈdjɑn ɔɾə'],
['ծնունդ ','birth','ʦənund'],
['հազար ինը հարյուր','1900','hɑˈzɑɾ inə hɑɾˈjuɾ'],
['համ-','same','hɑm'],
['համազգային','all-national','hɑmɑzɡɑˈjin'],
['համալիր','complex','hɑmɑˈliɾ'],
['համաքաղաքացի','fellow citizen','hɑmɑkʰɑʁɑkʰɑˈʦʰi'],
['հասցե','address','hɑsˈʦʰɛ'],
['ութսունվեց','86','utʰsunˈvɛʦʰ'],
['հունվարի մեկ','January 1st','hunvɑˈɾi mɛk'],
['ձեր','your (pl)','ʣɛɾ'],
['մատներ','fingers','mɑtˈnɛɾ'],
['յոթանասունչորս','74','jɔtʰɑnɑsunˈʧʰɔɾs'],
['որ','which','vɔɾ'],
['որն է','which is','ˈvɔɾn ‿ ɛ'],
['որոնք','which (pl)','vɔˈɾɔŋkʰ'],
['պողոտա','avenue','pɔʁɔˈtɑ'],
['սխալ','wrong','səˈχɑl'],
['սխալ հասցե','wrong address','səˈχɑl hɑsˈʦʰɛ'],
['վայր','place','vɑjɾ'],
['վայր դնել','to put down','vɑjɾ dənɛl'],
['վայր*','down','vɑjɾ'],
['տասը','ten','tɑsə'],
['տասը մատ','ten fingers','tɑsə mɑt'],
['քաղաքացի','citizen','kʰɑʁɑkʰɑˈʦʰi'],
['օգնել','to help','ɔkʰˈnɛl'],
['օգնություն','help','ɔkʰnuˈʦʰjun'],
['օգնություն խնդրել','to ask for help','ɔkʰnuˈʦʰjun χəntʰˈɾɛl']];