var u = [
['-անոց','noun of place','ɑˈnɔt͡sʰ'],
['-արան','place of','ɑˈɾɑn'],
['-ություն','abstract or collective noun','uˈtʰjun'],
['-ստան','nouns with the meaning of place','sˈtɑn'],
['այդ','that*','ɑjd'],
['այս տարի','this year','ɑjs  tɑˈɾi'],
['անգլերեն','English','ɑŋɡlɛˈɾɛn'],
['անգլիա','England','ˈɑŋɡlijɑ'],
['անցյալ ձմեռ','past winter','ɑnt͡sʰˈjɑl d͡zəˈmɛr'],
['անցյալ տարի','last year','ɑnt͡sʰˈjɑl tɑˈɾi'],
['աշխատանք','work','ɑʃχɑˈtɑŋkʰ'],
['աշխատել','to work','ɑʃχɑˈtɛl'],
['աշխատում ես','you are working','ɑʃχɑˈtum ɛs'],
['առավոտ','morning','ɑrɑˈvɔt'],
['ավարտ','finish','ɑˈvɑɾt'],
['ավարտել','to finish','ɑvɑɾˈtɛl'],
['ավարտել եմ համալսարանը','I graduated from the university','ɑvɑɾˈtɛl ɛm hɑmɑlsɑˈɾɑnə'],
['արդեն','already','ɑɾˈtʰɛn'],
['արդեն մեծ եմ','I am already adult','ɑɾˈtʰɛn mɛt͡s ɛm'],
['բավական','enough','bɑvɑˈkɑn'],
['բավական է','it is enough','bɑvɑˈkɑn ɛ'],
['բավականություն','pleasure','bɑvɑkɑnuˈt͡sʰjun'],
['բավականություն եմ ստանում','I get enjoy','bɑvɑkɑnuˈt͡sʰjun ɛm stɑˈnum'],
['բժիշկ','doctor','bəˈʒiʃk'],
['բժիշկ եմ','I am a doctor','bəˈʒiʃk ɛm'],
['բժշկություն ','medicine','bəʒəʃkuˈt͡sʰjun'],
['գերմաներեն','Germans','ɡɛɾmɑnɛˈɾɛn'],
['գերմանիա','Germany','ɡɛɾˈmɑnjɑ'],
['գիտեմ','I know','ɡiˈtɛm'],
['գիտենալ','to know','ɡitɛˈnɑl'],
['գիտես','you know','ɡiˈtɛs'],
['գիտի','he know','ɡiˈti'],
['դա','that','dɑ'],
['իմ մայրենի լեզուն','my mother tongue','im mɑjɾɛˈni lɛˈzun'],
['դիզայներ','designer','dizɑjˈnɛɾ'],
['դու կցանկանայիր','would you like','du kət͡sʰɑŋkɑnɑˈjiɾ'],
['դուր գալ','to be pleasant','duɾ ɡɑl'],
['դպրոց','school','dəpˈɾɔt͡sʰ'],
['դպրոցն ավարտել ես','have you finished school','dəpˈɾɔt͡sʰ ɑvɑɾˈtɛl ɛs'],
['երևում','appearance','jɛɾɛˈvum'],
['զբաղվել','be busy with','zbɑʁˈvɛl'],
['էլ','too','ɛl'],
['էլ*','also','ɛl'],
['ընդունել','to accept','əntʰunˈnɛl'],
['ընդունվել','to be accepted','əntʰunˈvɛl'],
['ընդունվել եմ','I have been accepted','əntʰunˈvɛl ɛm'],
['ընդունվել եմ քոլեջ','I entered college','əntʰunˈvɛl ɛm kʰɔˈlɛd͡ʒ'],
['ընկեր','friend','əŋˈkɛɾ'],
['ընկերություն','friendship','əŋkɛɾuˈt͡sʰjun'],
['ընկերություն*','company','əŋkɛɾuˈt͡sʰjun'],
['ընտրել','to choose','əntˈɾɛl'],
['ժողովուրդ','people','ʒɔʁɔˈvuɾtʰ'],
['ժողովրդական','folk','ʒɔʁɔvəɾtʰɑˈkɑn'],
['ժողովրդական բժշկություն','folk medicine','ʒɔʁɔvəɾtʰɑˈkɑn bəʒəʃkuˈt͡sʰjun'],
['իհարկե','of course','iˈhɑɾkɛ'],
['իմ','my','im'],
['ինժեներ','engineer','inʒɛˈnɛɾ'],
['ինժեներ եմ','I am an engineer','inʒɛˈnɛɾ ɛm'],
['ինձ դուր է գալիս','I like it','ind͡z duɾ ɛ ɡɑˈlis'],
['ինչ կրթություն ունես','what education do you have','int͡ʃʰ kəɾtʰuˈt͡sʰjun uˈnɛs'],
['ինչով','with what','int͡ʃʰɔv'],
['ինչով ես զբաղվում','what do you do','int͡ʃʰɔv ɛs zbɑʁˈvum'],
['ինչու ես ընտրել','why did you choose','inˈt͡ʃʰu ɛs əntˈɾɛl'],
['այդ մասնագիտությունը','that profession','ɑjd mɑsnɑɡituˈt͡sʰjunə'],
['իսկապես','indeed','iskɑˈpɛs'],
['իսպաներեն','Spanish','ispɑnɛˈɾɛn'],
['իսպանիա','Spain','isˈpɑnjɑ'],
['լեզու','tongue','lɛˈzu'],
['լեզու*','language','lɛˈzu'],
['լեզուներ ուսումնասիրելիս','studying languages','lɛzuˈnɛɾ usumnɑsiɾɛˈlis'],
['լրանալ','to be finished','lɾɑˈnɑl'],
['խոսել','to speak','χɔˈsɛl'],
['խոսում ես ռուսերեն','you speak Russian','χɔˈsum ɛs rusɛˈɾɛn'],
['կրթել','to educate','kəɾˈtʰɛl'],
['կրթություն','education','kəɾtʰuˈt͡sʰjun'],
['կցանկանայիր սովորել','would you like to learn','kət͡sʰɑŋkɑnɑˈjiɾ sɔvɔˈɾɛl'],
['համ-','whole','hɑm'],
['համ-*','same','hɑm'],
['համալսարան','university','hɑmɑlsɑˈɾɑn'],
['հասակ','age of person','hɑˈsɑk'],
['հիվանդ','ill','hiˈvɑnd'],
['հիվանդ*','patient','hiˈvɑnd'],
['հիվանդանոց','hospital','hivɑndɑˈnɔt͡sʰ'],
['հիվանդանոցում','in the hospital','hivɑndɑnɔˈt͡sʰum'],
['ձմեռ','winter','d͡zəˈmɛr'],
['մայրենի','maternal','mɑjɾɛˈni'],
['մայրենի լեզու','native language','mɑjɾɛˈni lɛˈzu'],
['մանուկ','child','mɑˈnuk'],
['մանուկ հասակից','since childhood','mɑˈnuk hɑsɑˈkit͡sʰ'],
['մաս','part','mɑs'],
['մաս*','bit','mɑs'],
['մասնագետ','specialist','mɑsnɑˈɡɛt'],
['մասնագիտություն','profession','mɑsnɑɡituˈt͡sʰjun'],
['մեծ','big','mɛt͡s'],
['մեծ*','adult','mɛt͡s'],
['նա քո ընկերն է','he is your boyfriend','nɑ kɔ əŋˈkɛɾn ɛ'],
['նկարել','to photograph','nəkɑˈɾɛl'],
['նկարել*','to paint','nəkɑˈɾɛl'],
['նկարել**','to shoot a video','nəkɑˈɾɛl'],
['շատ','much','ʃɑt'],
['շատ*','a lot of','ʃɑt'],
['շինանյութ','building material','ʃinɑnˈjutʰ'],
['շինարար','builder','ʃinɑˈɾɑɾ'],
['շինարարական ընկերությունում','in construction company','ʃinɑɾɑɾɑˈkɑn əŋkɛɾut͡sʰjuˈnum'],
['շուտով քսանյոթս կլրանամ','I will soon turn 27','ʃuˈtɔv kʰəsɑnˈjɔtʰəs kəlɾɑˈnɑm'],
['որ մասնագիտությունն','which profession','vɔɾ mɑsnɑɡituˈt͡sʰjunː'],
['որն ես ընտրել','which did you choose','vɔɾn  ɛs əntˈɾɛl'],
['որն է քո','which is yours','vɔɾn ɛ kʰɔ'],
['քո մասնագիտությունը','your profession','kʰɔ mɑsnɑɡituˈt͡sʰjunə'],
['որովհետև','because','vɔɾɔfhɛˈtɛv'],
['որտեղ ես աշխատում','where do you work','vɔɾˈtɛʁ ɛs ɑʃχɑˈtum'],
['որևէ','any','ˈvɔɾɛvɛ'],
['օտար լեզու','foreign language','ɔˈtɑɾ lɛˈzu'],
['ուզել','to want','uˈzɛl'],
['ուզում եմ','I want','uˈzum ɛm'],
['ուզում եմ փոխել','I want to change','uˈzum ɛm pʰɔˈχɛl'],
['մասնագիտությունս','my profession','mɑsnɑɡituˈt͡sʰjunəs'],
['ութ','eight','utʰ'],
['ուսումնասիրել','to study','usumnɑsiˈɾɛl'],
['ուսումնասիրել*','to investigate','usumnɑsiˈɾɛl'],
['ուրեմն','therefore','uˈɾɛmən'],
['ուրեմն քսանվեց ես','so you are 26','uˈɾɛmən kʰəsɑnˈvɛt͡sʰ ɛs'],
['ուրիշ','another','uˈɾiʃ'],
['ուրիշ էլ ինչ','what else','uˈɾiʃ ɛl int͡ʃʰ'],
['չեմ խոսում','I do not speak','t͡ʃʰɛm χɔˈsum'],
['չի կարող','can not','t͡ʃʰi kɑˈɾɔʁ'],
['չի կարող պատահել','can not happen','t͡ʃʰi kɑˈɾɔʁ pɑtɑˈhɛl'],
['չինաստան','China','t͡ʃʰinɑsˈtɑn'],
['չինարեն','chinese','t͡ʃʰinɑˈɾɛn'],
['պատահել','to happen','pɑtɑˈhɛl'],
['պատահել*','to occur','pɑtɑˈhɛl'],
['ռուս','russian person ','rus'],
['ռուսերեն','russian','rusɛˈɾɛn'],
['սիրում եմ նկարել','I like to paint','siˈɾum ɛm nəkɑˈɾɛl'],
['սովորել','to study*','sɔvɔˈɾɛl'],
['սովորելը','studying','sɔvɔˈɾɛlə'],
['սուրճ','coffee','suɾt͡ʃ'],
['ստանալ','to receive','stɑˈnɑl'],
['սրճարան','café','səɾt͡ʃɑˈɾɑn'],
['վաղ','early','vɑʁ'],
['վաղ առավոտյան','early in the morning','vɑʁ ɑrɑvɔtˈjɑn'],
['վաղուց','long ago','vɑˈʁut͡sʰ'],
['վաղուց ես նկարում','you painting for a long time','vɑˈʁut͡sʰ ɛs nəkɑˈɾum'],
['տասներեք','thirteen','tɑsnɛˈɾɛkʰ'],
['տասներկու','twelve','tɑsnɛɾˈku'],
['տասնհինգ','fifteen','tɑsnəˈhiŋɡ'],
['տասնութ','eighteen','tɑsnəˈutʰ'],
['տասնչորս','fourteen','tɑsnəˈt͡ʃʰɔɾs'],
['տասնվեց','sixteen','tɑsnəˈvɛt͡sʰ'],
['տարի','year','tɑˈɾi'],
['ցանկ','list','t͡sʰɑŋk'],
['ցանկ*','table of contents','t͡sʰɑŋk'],
['ցանկանալ','to desire','t͡sʰɑŋkɑˈnɑl'],
['փոխել','to change','pʰɔˈχɛl'],
['փոխել*','to exchange','pʰɔˈχɛl'],
['փոքր','small ','ˈpʰɔkʰəɾ'],
['փոքր ես երևում','you look small','ˈpʰɔkʰəɾ ɛs jɛɾɛˈvum'],
['քանի տարեկան ես','how old are you','kʰɑˈni tɑɾɛˈkɑn ɛs'],
['քանի տարով','for how many years','kʰɑˈni tɑˈɾov'],
['քեզ դուր է գալիս','do you like','kʰɛz duɾ ɛ ɡɑˈlis'],
['դուր է գալիս սովորելը','to like studying','duɾ ɛ ɡɑˈlis sɔvɔˈɾɛlə'],
['քեզնից','than you','kʰɛzˈnit͡sʰ'],
['քեզնից մեծ եմ','I am older than you','kʰɛzˈnit͡sʰ mɛt͡s ɛm'],
['քսան','twenty','kʰəˈsɑn'],
['քսանյոթս կլրանամ','I will turn 27','kʰəsɑnˈjɔtʰəs kəlɾɑˈnɑm'],
['քսանվեց','26','kʰəsɑnˈvɛt͡sʰ'],
['օտար','foreign','ɔˈtɑɾ'],
['ֆրանսերեն','French','fɾɑnsɛˈɾɛn'],
['ֆրանսիա','France','ˈfɾɑnsjɑ']];