var u=[
['այո','yes','ɑˈjɔ'],
['ապրել','to live','ɑpˈɾɛl'],
['ապրել*','to exist','ɑpˈɾɛl'],
['ապրել**','to reside','ɑpˈɾɛl'],
['բնակարան','apartment','bənɑkɑˈɾɑn'],
['բնակարանում','in apartment','bənɑkɑɾɑˈnum'],
['գյուղ','village','գյուղ'],
['գյուղում','in village','գյուˈղում'],
['դու հայ ես','you are Armenian','du haj ‿ ɛs'],
['ես','are','ɛs'],
['ես ունեմ տուն','I have a house','jɛs unɛm tun'],
['ես*','I','jɛs'],
['իսկ դու','but you','isk du'],
['մենակ','alone','mɛˈnɑk'],
['մենակ ես','are you alone','mɛˈnɑk ‿ ɛs'],
['ոչ','not','vɔʧʰ'],
['որտեղ','where','vɔɾˈtɛʁ'],
['որտեղ ես ապրում','where do you live','vɔɾˈtɛʁ ‿ ɛs ɑpˈɾum'],
['չորս','four','ʧʰɔɾs'],
['չորսով ենք','there are four of us','ʧʰɔɾˈsov ‿ ɛŋkʰ'],
['տասնմեկ','eleven','tɑsnəˈmɛk'],
['տուն ունես','do you have a house','tun uˈnɛs'],
['փոքր','small','ˈpʰɔkʰəɾ'],
['փոքր քաղաքում','in small town','ˈpʰɔkʰəɾ kʰɑʁɑˈkʰum'],
['փոքր*','junior','ˈpʰɔkʰəɾ'],
['քաղաք','town','kʰɑˈʁɑkʰ'],
['քաղաքում','in town','kʰɑʁɑˈkʰum']];