var u=[
['այո','yes','ɑˈjɔ'],
['աշխատանք','job','ɑʃχɑˈtɑŋkʰ'],
['բժիշկ','doctor','bəˈʒiʃk'],
['բժիշկդ','your doctor','bəˈʒiʃkət'],
['բժիշկս','my doctor','bəˈʒiʃkəs'],
['դուր գալ','to be pleasant','duɾ ɡɑl'],
['դուր է գալիս','like it','ˈduɾ ‿ ɛ ɡɑˈlis'],
['զբաղվել','be busy with','zbɑʁˈvɛl'],
['ընկեր','friend','əŋˈkɛɾ'],
['ընկերդ','your friend','əŋˈkɛɾət'],
['ընկերություն','company','əŋkɛɾuˈʦʰjun'],
['ընկերություն*','friendship','əŋkɛɾuˈʦʰjun'],
['ընկերությունում','in company','əŋkɛɾuʦʰjuˈnum'],
['ընկերս','my friend','əŋˈkɛɾəs'],
['ինժեներ','engineer','inʒɛˈnɛɾ'],
['ինչ','what','inʧʰ'],
['ինչով ես զբաղվում','what do you do','inˈʧʰɔv ‿ ɛs zbɑʁˈvum'],
['իսկ դու','what about you*','isk du'],
['իսկ քեզ','what about you','isk kʰɛz'],
['հիվանդ','patient','hiˈvɑnd'],
['հիվանդ*','ill','hiˈvɑnd'],
['հիվանդանոց','hospital','hivɑndɑˈnɔʦʰ'],
['հիվանդանոցում','in hospital','hivɑndɑnɔˈʦʰum'],
['մասնագիտություն','profession','mɑsnɑɡituˈʦʰjun'],
['մասնագիտությունս','my profession','mɑsnɑɡituˈʦʰjunəs'],
['շատ','much','ʃɑt'],
['շինարար','builder','ʃinɑˈɾɑɾ'],
['շինարարական','builderˈs','ʃinɑɾɑɾɑˈkɑn'],
['աշխատել','to work','ɑʃχɑˈtɛl'],
['ոչ','no','vɔʧʰ'],
['որտեղ','where','vɔɾˈtɛʁ'],
['ուզել','to want','uˈzɛl'],
['սեր','love','sɛɾ'],
['սիրել','to love','siˈɾɛl'],
['սիրով զբաղվել',' to make love','siˈɾɔv zbɑʁˈvɛl'],
['տասնհինգ','fifteen','zəˈɾujʦʰ tɑsnəˈhiŋɡ'],
['փոխել','to change','pʰɔˈχɛl'],
['քեզ','to you','kʰɛz']];