var u=[
['անգլերենի','in English','ɑŋɡlɛɾɛˈni'],
['ապրում եմ','I live','ɑpˈɾum ‿ ɛm'],
['ապրում եք','you live','ɑpˈɾum ‿ ɛkʰ'],
['առանձին','apart','ɑrɑnˈʣin'],
['առանձին բան չէ','itˈs not important','ɑrɑnˈʣin bɑn ʧʰɛ'],
['ավանդել','to teach*','ɑvɑnˈdɛl'],
['դաս','category','dɑs'],
['դաս*','lesson','dɑs'],
['դասավանդել','to teach','dɑsɑvɑnˈdɛl'],
['դուք ունեք','you have','dukʰ uˈnɛkʰ'],
['ես նույնպես','me too','jɛs ˈnujnpɛs'],
['ես ունեմ','I have','ɛs uˈnɛm'],
['երաժիշտ','musician','jɛɾɑˈʒiʃt'],
['երաժիշտ է','he is musician','jɛɾɑˈʒiʃt ‿ ɛ'],
['երաժշտություն','music','jɛɾɑʒəʃtuˈʦʰjun'],
['զբաղվում է','he engaged in','zbɑʁˈvum ‿ ɛ'],
['զբաղվել','be busy with','zbɑʁˈvɛl'],
['զբաղվել*','be occupied with','zbɑʁˈvɛl'],
['ընտանի','domestic','əntɑˈni'],
['ինչով','with what','inˈʧʰɔv'],
['ծնողների հետ','with parents','ʦənɔʁnɛˈɾi ˈhɛt'],
['ծնողներ','parents','ʦənɔʁˈnɛɾ'],
['ծնող','parent','ʦəˈnɔʁ'],
['ձեր հայրը','your father','ʣɛɾ hɑjɾə'],
['ձեր մայրը','your mother','ʣɛɾ mɑjɾə'],
['մեծ','big','mɛʦ'],
['մեծ շուն','big dog','mɛʦ ʃun'],
['մեծ քար','large stone','mɛʦ kʰɑɾ'],
['մեծ*','large','mɛʦ'],
['նա','he','nɑ'],
['նա*','it','nɑ'],
['նա**','she','nɑ'],
['նույնպես','also','ˈnujnpɛs'],
['նրանցից','of them','nəɾɑnˈʦʰiʦʰ'],
['նրանցից*','from them','nəɾɑnˈʦʰiʦʰ'],
['նրանցից**','with them','nəɾɑnˈʦʰiʦʰ'],
['նրանք','they','nəɾɑŋˈkʰ'],
['ուսուցիչ','teacher','usuˈʦʰiʧʰ'],
['ուսուցչուհի','female teacher','usuʦʰʧʰuˈhi'],
['տասնյոթ','seventeen','tɑsnəˈjɔtʰ'],
['տուն','home','tun'],
['տուն*','house','tun']];