var u=[
['անգլերեն','English','ɑŋɡlɛˈɾɛn'],
['բավական','enough','bɑvɑˈkɑn'],
['բավականություն','pleasure','bɑvɑkɑnuˈʦʰjun'],
['գերմաներեն','German','ɡɛɾmɑnɛˈɾɛn'],
['գիտես','you know','ɡiˈtɛs'],
['դա','that','dɑ'],
['էլ','any more','ɛl'],
['էլ*','also','ɛl'],
['ըստ','according to','əst'],
['ըստ սովորության','by habit','əst sɔvɔɾuˈʦʰjun'],
['իհարկե','of course','iˈhɑɾkɛ'],
['իմ','my','im'],
['ինչ','what','inʧʰ'],
['իսկապես','indeed','iskɑˈpɛs'],
['իսպաներեն','Spanish','ispɑnɛˈɾɛn'],
['լեզու','tongue','lɛˈzu'],
['լեզու*','language','lɛˈzu'],
['լեզուներ','languages','lɛzuˈnɛɾ'],
['խոսել','to speak','χɔˈsɛլ'],
['խոսում ես','you speak','χɔˈsum ‿ ɛs'],
['կցանկանայիր','would you like*','kəʦʰɑŋkɑnɑˈjiɾ'],
['համ-','same','hɑm'],
['համաձայն','in accord','hɑmɑˈʣɑjn'],
['ձայն','voice','ʣɑjn'],
['ձայն*','sound','ʣɑjn'],
['մայրենի','motherˈs','mɑjɾɛˈni'],
['մայրենի լեզու','mother tongue','mɑjɾɛˈni lɛˈzu'],
['մայրենի*','maternal','mɑjɾɛˈni'],
['մեծ բավականությամբ','with pleasure','mɛtʦ bɑvɑkɑnuˈʦʰjɑmb'],
['ոչ','no','vɔʧʰ'],
['որևէ','any','ˈvɔɾɛvɛ'],
['ուսում','education','uˈsum'],
['ուսումնասեր','studious','usumnɑˈsɛɾ'],
['ուսումնասիրել','to study','usumnɑsiˈɾɛl'],
['ուսուցիչ','teacher','usuˈʦʰiʧʰ'],
['ուրիշ','other','uˈɾiʃ'],
['ուրիշ*','anther','uˈɾiʃ'],
['չեմ խոսում','donˈt speak','ʧʰɛm ‿ χɔˈsum'],
['չինարեն','Chinese','ʧʰinɑˈɾɛn'],
['ռուսերեն','russian','rusɛˈɾɛn'],
['սովոր','used to','sɔˈvɔɾ'],
['սովոր*','usual','sɔˈvɔɾ'],
['սովորաբար','usually','sɔvɔɾɑˈbɑɾ'],
['սովորական','common','sɔvɔɾɑˈkɑn'],
['սովորել','to learn','sɔvɔˈɾɛl'],
['սովորել*','to study*','sɔvɔˈɾɛl'],
['սովորության համաձայն','according to habit','sɔvɔɾuˈʦʰjɑn hɑmɑˈʣɑjn'],
['սովորություն','habit','sɔvɔɾuˈʦʰjun'],
['ստանալ','to receive','stɑˈnɑl'],
['վատ սովորություն','bad habit','vɑt sɔvɔɾuˈʦʰjun'],
['տասնվեց','sixteen','tɑsnəˈvɛʦʰ'],
['ցանկ','table of contents','ʦʰɑŋk'],
['ցանկանալ','to wish','ʦʰɑŋkɑˈnɑl'],
['ցանկանայիր','would you like','ʦʰɑŋkɑnɑˈjiɾ'],
['օտար','foreign','ɔˈtɑɾ'],
['օտար լեզու','foreign language','ɔˈtɑɾ lɛˈzu'],
['օտար*','foreigner','ɔˈtɑɾ'],
['ֆրանսերեն','French','fɾɑnsɛˈɾɛn']];