var u=[
['ամբողջ գիշեր','all night','ɑmˈboχʧʰ ɡiˈʃɛɾ'],
['այս անգամ','this time','ɑjs ɑŋˈkʰɑm'],
['անգամ','times','ɑŋˈkʰɑm'],
['անկեղծ','honest','ɑŋˈkɛχʦ'],
['անկեղծ ասաց','said honestly','ɑŋˈkɛχʦ ɑˈsɑʦʰ'],
['ասաց','said','ɑˈsɑʦʰ'],
['արթնանալ','to wake up','ɑɾtʰnɑˈnɑl'],
['գիշեր','night','ɡiˈʃɛɾ'],
['դայակ','nurse','dɑˈjɑk'],
['լավ եք','how are you','ˈlɑv ‿ ɛkʰ'],
['լավ եք քնում','do you sleep well','ˈlɑv ‿ ɛkʰ kʰəˈnum'],
['խնամել','to care for','χənɑˈmel'],
['կարողանալ','to be able','kɑɾoʁɑˈnɑl'],
['կարողանում ենք','we can','kɑɾɔʁɑˈnum ‿ ɛŋkʰ'],
['կերակրել','to feed','keɾɑkˈɾel'],
['կինս','my wife','ˈkinəs'],
['հաճախ','often','hɑˈʧɑχ'],
['հոգ','care','hɔkʰ'],
['հոգ տանել','take care','hɔkʰ tɑˈnɛl'],
['ձեր նորածնին','for your newborn','ʣɛɾ nɔɾɑʦənˈin'],
['մի անգամ','once','mi ɑŋˈkʰɑm'],
['մի քանի','few','mi kɑˈni'],
['մի քանի անգամ','several times','mi kɑˈni ɑŋˈkʰɑm'],
['մութ գիշեր','dark night','mutʰ ɡiˈʃɛɾ'],
['նորածին','newborn','nɔɾɑˈʦin'],
['որքան','how much','vɔɾˈkʰɑn'],
['որքան հաճախ','how often','vɔɾˈkʰɑn hɑˈʧɑχ'],
['որքան*','how','vɔɾˈkʰɑn'],
['ունեք','you have','unɛkʰ'],
['ստիպվել','to be forced to','stipˈvel'],
['վերջին անգամ','last time','veɾˈʧʰin ɑŋˈkʰɑm'],
['քնել','to sleep','kʰəˈnel'],
['քսան','twenty','kʰəˈsɑn'],
['օրը մի քանի անգամ','several times a day','ɔɾə mi kɑˈni ɑŋˈkʰɑm']];