var u=[
['այս','this','ɑjs'],
['ապրել','to live','ɑpˈɾel'],
['ապրել*','to exist','ɑpˈɾel'],
['ապրել**','to stay','ɑpˈɾel'],
['գյուղ','village','ɡjuʁ'],
['զարմիկ','cousin (male)','zɑɾˈmik'],
['զարմուհի','cousin (female)','zɑɾmuˈhi'],
['թե','then','tʰe'],
['թե*','or','tʰe'],
['թե**','if','tʰe'],
['լավ','good','lɑv'],
['հարաբերություն','relation','hɑɾɑbeɾuˈtʰjun'],
['հետ','back','het'],
['հետ*','with','het'],
['մանկուց','since childhood','mɑˈnkunʦʰ'],
['մանուկ','child','mɑˈnuk'],
['մեծ','big','meʦ'],
['մեծ*','elder','meʦ'],
['մեջ','inside','meʧʰ'],
['մեջ*','among','meʧʰ'],
['մի','one','mi'],
['մի*','some','mi'],
['մի**','donˈt','mi'],
['մնալ','to stay*','məˈnɑl'],
['մնալ*','to remain','məˈnɑl'],
['մնացած','the rest','mənɑˈʦʰɑʦ'],
['նրանց','their','nəˈɾɑnʦʰ'],
['նրանց*','them','nəˈɾɑnʦʰ'],
['նրանք','they are','են'],
['փոքր','small','pʰokʰəɾ'],
['փոքր*','younger','pʰokʰəɾ'],
['քաղաքում','in city','kʰɑˈʁɑkʰum'],
['քեզնից','from you','kʰezˈniʦʰ'],
['քեզնից*','then you','kʰezˈniʦʰ'],
['քույր','sister','kʰujɾ'],
['քույրս','my sister','kʰujɾs']];