 var u=[
['ամուսին','husband','ɑmuˈsin'],
['ամուսնալուծություն','divorce','ɑmusnɑluʦuˈʦʰjun'],
['ամուսնալուծված','divorced','ɑmusnɑluʦˈvɑʦ'],
['լուծել','to solve','luʦel'],
['ամուսնանալ','to marry','ɑmusnɑˈnɑl'],
['ամուսնացած','married','ɑmusnɑˈʦʰɑʦ'],
['ավագ','elder','ɑˈvɑkʰ'],
['ավագ եղբայր','elder brother','ɑˈvɑkʰ jɛχˈpɑjɾ'],
['ավարտել','to finish','ɑvɑɾˈtel'],
['ավարտվել','to be finished','ɑvɑɾtˈvel'],
['ավարտվում են','are ending','ɑvɑɾtˈvum ‿ ɛn'],
['բաժանել','to divide','bɑʒɑˈnel'],
['բաժանությամբ','by division','bɑʒɑnuˈʦʰjamb'],
['բաժանություն','division','bɑʒɑnuˈʦʰjun'],
['բաժանում','parting','bɑʒɑˈnum'],
['եղբայր','brother','jeχˈpɑjɾ'],
['եղել','been','jɛˈʁɛl'],
['լինել','to be','liˈnel'],
['կրտսեր','younger','kəɾtˈseɾ'],
['կրտսեր քույր','younger sister','kəɾtˈsɛɾ kʰujɾ'],
['հիմա','now','hiˈmɑ'],
['մեր օրերում','in our days','mɛɾ ɔɾɛˈɾum'],
['ունեի','I had','uneˈji'],
['ունեիր','you had','uneˈjiɾ'],
['ունեմ','I have','uˈnem'],
['ունես','you have','uˈnes'],
['ուներ','he had','uˈneɾ'],
['ունի','he has','uˈni'],
['տասն','ten','tɑsn'],
['տասնինը','nineteen','tɑsˈninə'],
['տարեկան','year-old','tɑrɛˈkɑn'],
['քանի տարեկան է','how old','kɑˈni tɑrɛˈkɑn ‿ ɛ'],
['քանի','how many','kɑˈni'],
['քույր','sister','kʰujɾ'],
['քսանմեկ','twenty one','kʰəsɑnˈmɛk']];