var u=[
['այո','yes','ɑˈjɔ'],
['այրի','widow','ɑjˈɾi'],
['այրի կին','widow','ɑjˈɾi kin'],
['այրի տղամարդ','widower','ɑjˈɾi təʁɑˈmɑɾtʰ'],
['առողջ','healthy','ɑˈrɔχʧʰ'],
['առողջություն','health','ɑˈrɔχʧʰutjun'],
['բայց','but','bɑjʦʰ'],
['բոլոր','all','bɔˈlɔɾ'],
['գյուղ','village','ɡjuʁ'],
['թաղել','to bury','tʰɑˈʁel'],
['թաղված','buried','tʰɑʁˈvɑʦ'],
['թաղվել','to be buried','tʰɑʁˈvel'],
['իրենց','their','iˈɾɛŋʦʰ'],
['իրենց*','them','iˈɾɛŋʦʰ'],
['իրենց**','themselves','iˈɾɛŋʦʰ'],
['խնամել','to care for','χənɑˈmel'],
['հարյուր','hundred','hɑɾˈjuɾ'],
['մահանալ','to die','mɑhɑˈnɑl'],
['մահացել','died','mɑhɑˈʦʰɛl'],
['նախա-','pre-','nɑχɑ'],
['նախ','first','nɑχ'],
['նախ*','in the first place','nɑχ'],
['նախա-*','fore-','nɑχɑ'],
['նախատատ','fore-mother','nɑχɑˈtɑt'],
['ողջ','whole','ˈvɔχʧʰ'],
['ողջ*','alive','ˈvɔχʧʰ'],
['ողջ*','safe','ˈvɔχʧʰ'],
['ոչ','not','vɔʧʰ'],
['ոչ ոք','nobody','vɔʧʰ vɔkʰ'],
['ուրեմն','therefore','uˈɾɛmən'],
['պապ','grandfather','pɑp'],
['պապիկ','grandpa','pɑˈpik'],
['տատ','grandmother','tɑt'],
['տատիկ','grandma','tɑˈtik'],
['տարեկան','year-old','tɑɾɛˈkɑn'],
['քանի','how many','kʰɑˈni'],
['քաջ','excellent','kʰɑʤ'],
['քաջ առողջություն','good health','kʰɑʤ ɑˈrɔχʧʰutjun'],
['քաջառողջ','very healthy','kʰɑʤɑˈrɔχʧʰ'],
['քսաներկու','twenty-two','kʰəsɑnɛɾˈku']];