var u=[
['քսաներեք','twenty-three','kʰəsɑneˈɾekʰ'],
['մորաքույր','maternal aunt','du moɾɑˈkʰujɾ'],
['մորեղբայր','maternal uncle','moɾeχˈpɑjɾ'],
['քեռի','maternal uncle*','kʰeˈri'],
['կամ','or','kɑm'],
['կամ*','I am','kɑm'],
['հորաքույր','paternal aunt','hoɾɑˈkʰujɾ'],
['հորեղբայր','paternal uncle','hoɾeχˈpɑjɾ'],
['ունես','you have','uˈnes'],
['ունենք','we have','uˈneŋkʰ'],
['ունեք','you have (pl)','uˈnekʰ'],
['ունեն','they have','uˈnen'],
['նրանք','they','nəˈɾɑŋkʰ'],
['որտեղ','where','voɾˈteʁ'],
['ապրել','to live','ɑpˈɾel'],
['քաղաք','city','kʰɑˈʁɑkʰ'],
['հաճախ','often','hɑˈʧɑχ'],
['տեսնվել','to meet','tesnəˈvel'],
['վաղը կտեսնվենք','we will meet tomorrow','vɑʁə tesnəˈvenkʰ'],
['վաղը','tomorrow','vɑʁə'],
['տարի','year','tɑˈɾi'],
['անգամ','an occurrence','ɑŋˈkʰɑm'],
['ինչու','why','inˈʧʰu'],
['այդքան','so','ɑjtkʰɑn'],
['հազվադեպ','rarely','hɑzvɑˈdep'],
['հազիվ','just','hɑˈziv'],
['հազիվ թե','hardly','hɑˈziv tʰe'],
['որովհետև','because','voɾofheˈtev'],
['ազատ','free','ɑˈzɑt'],
['ժամանակ','time','ʒɑmɑˈnɑk']];