var u = [
['սանկտ պետերբուրգ','Saint Peterburg','sɑnkt pɛtɛɾˈbuɾg'],
['տուն ունես','do you have a house','tun uˈnɛs'],
['լոնդոնում','in London','lɔndɔˈnum'],
['այժմ','ˈɑjʒəm','now'],
['ապրիլ','April','ɑpˈɾil'],
['ես ծնվել եմ','I was born','jɛs t͡sənˈvɛl ɛm'],
['մոսկվա','Moscow','mɔskˈvɑ'],
['նևսկի պողոտա','Nevsky avenue','nɛvˈski pɔʁɔˈtɑ'],
['նյու յորք','New York','nju jɔɾkʰ'],
['միացյալ նահանգներ','United States','mijɑt͡sʰˈjɑl nɑhɑŋɡˈnɛɾ'],
['ծանոթություն','acquaintance','t͡sɑnɔtʰuˈt͡sʰjun'],
['հասցե','address','hɑsˈt͡sʰɛ'],
['մենակ','alone','mɛˈnɑk'],
['իսկ դու','and you','isk du'],
['իսկ քոնը','and yours','isk ˈkʰɔnə'],
['բնակարան','apartment','bənɑkɑˈɾɑn'],
['ծնունդ','birth','t͡səˈnund'],
['ծննդյան օր','birthday','t͡sənəndjɑn ɔɾ'],
['ծննդավայր','birthplace','t͡sənəndɑˈvɑjɾ'],
['քաղաքացի','citizen','kʰɑʁɑkʰɑˈt͡sʰi'],
['քաղաք','city','kʰɑˈʁɑkʰ'],
['երկիր','country','jɛɾˈkiɾ'],
['ծննդյան ամսաթիվը','date of birth','t͡sənəndjɑn ɑmsɑˈtʰivə'],
['ամսաթիվ','date of month','ɑmsɑˈtʰiv'],
['մենակ ես ապրում','do you live alone','mɛˈnɑk ɛs ɑpˈɾum'],
['վայր*','down','vɑjɾ'],
['տասնմեկ','eleven','tɑsnəˈmɛk'],
['ազգություն','ethnicity','ɑzɡuˈt͡sʰjun'],
['չորսով','four of us','t͡ʃʰɔɾˈsov'],
['մոսկվաից','from Moscow','mɔskvɑˈit͡sʰ'],
['նյու յորքից','from New York','nju jɔɾkʰˈit͡sʰ'],
['ռուսաստանից','from Russia','rusɑsˈtɑnit͡sʰ'],
['Միացյալ Նահանգներից','from the United States','mijɑt͡sʰˈjɑl nɑhɑŋɡnɛɾˈit͡sʰ'],
['որ քաղաքից','from which city','vɔɾ kʰɑʁɑkʰˈit͡sʰ'],
['բնակչություն','habitation','bənɑkt͡ʃʰuˈt͡sʰjun'],
['ունի','he has','uˈni'],
['տուն','house','tun'],
['ունեմ','i have','uˈnɛm'],
['ես ապրում եմ','i live','ɛs ɑpˈɾum ɛm'],
['ես ապրում եմ բնակարանում','i live in an apartment','ɛs ɑpˈɾum ɛm bənɑkɑɾɑˈnum'],
['երկու հազար թվականի','in 2000 year','jɛɾˈku hɑˈzɑɾ tʰəvɑkɑˈni'],
['ապրիլին','in April','ɑpɾiˈlin'],
['երկու հազար թվականի ապրիլին','in April of the year two thousand','jɛɾˈku hɑˈzɑɾ tʰəvɑkɑˈni ɑpɾiˈlin'],
['մոսկվայում','in Moscow','mɔskvɑˈum'],
['փոքր քաղաքում','in a small town','ˈpʰɔkʰəɾ kʰɑʁɑˈkʰum'],
['գյուղում','in a village','gjուˈʁum'],
['բնակարանում','in an apartment','bənɑkɑɾɑˈnum'],
['հազար իննը հարյուր թվականի','in the year 1900','hɑˈzɑɾ inːə hɑɾˈjuɾ tʰəvɑkɑˈni'],
['իննսունհինգ թվականի','in the year ninety-five','inːəsunˈhiŋɡ tʰəvɑkɑˈni'],
['հայ է','is Armenian','hɑj ɛ'],
['վայր','location','vɑjɾ'],
['ամիս','month','ɑˈmis'],
['հայրս','my father','hɑjɾəs'],
['հայրս հայ է','my father is Armenian','hɑjɾəs hɑj ɛ'],
['մայրս','my mother','mɑjɾəs'],
['մայրս ռուս է','my mother is Russian','mɑjɾəs rus ɛ'],
['հազար իննը հարյուր իննսունհինգ','nineteen ninety-five','hɑˈzɑɾ inːə hɑɾˈjuɾ inːəsunˈhiŋɡ'],
['թիվ','number','tʰiv'],
['ռուսաստանի','of Russia','rusɑstɑˈni'],
['բնակչություն*','population','bənɑkt͡ʃʰuˈt͡sʰjun'],
['նահանգ','province','nɑˈhɑŋɡ'],
['յոթանասունչորս','seventy-fourth','jɔtʰɑnɑsunˈt͡ʃʰɔɾs'],
['փոքր','small','ˈpʰɔkʰəɾ'],
['ուրեմն','so','uˈɾɛmən'],
['ուրեմն անգլիացի ես','so you are English','uˈɾɛmən ɑŋɡlijɑˈt͡sʰi ɛs'],
['ազգանուն','surname','ɑzɡɑˈnun'],
['ասեք ձեր ծննդավայրը','tell me your place of birth','ɑˈsɛkʰ d͡zɛɾ t͡sənəndɑˈvɑjɾə'],
['չորսով ենք','there are four of us','t͡ʃʰɔɾˈsov ɛŋkʰ'],
['ուրեմն*','therefore','uˈɾɛmən'],
['ժամանել','to arrive','ʒɑmɑˈnɛl'],
['խնդրել','to ask','χəntʰˈɾɛl'],
['ապրել','to live','ɑpˈɾɛl'],
['վայր դնել','to put down','vɑjɾ dəˈnɛl'],
['ասել','to say','ɑˈsɛl'],
['քաղաք*','town','kʰɑˈʁɑkʰ'],
['երկու հազար','two thousand','jɛɾˈku hɑˈzɑɾ'],
['միացյալ','united','mijɑt͡sʰˈjɑl'],
['գյուղ','village','ɡjuʁ'],
['ինչ է','what is','int͡ʃʰ ɛ'],
['որն է','what is*','vɔɾn ɛ'],
['որն է ձեր','what is your','vɔɾn ɛ d͡zɛɾ'],
['անունդ ինչ է','what is your name','ɑˈnunətʰ int͡ʃʰ ɛ'],
['ձեր անունն ինչ է','what is your name*','d͡zɛɾ ɑˈnunː int͡ʃʰ ɛ'],
['դու ինչ ազգության ես','what nationality are you	','du int͡ʃʰ ɑzɡuˈt͡sʰjɑn ɛs'],
['որտեղ','where','vɔɾˈtɛʁ'],
['որտեղից ես','where are you from','vɔɾˈtɛʁit͡sʰ ɛs'],
['որտեղից եք','where are you from*','vɔɾˈtɛʁit͡sʰ ɛkʰ'],
['որտեղից եք ժամանել','where did you come from','vɔɾˈtɛʁit͡sʰ ɛkʰ ʒɑmɑˈnɛl'],
['որտեղ ես ապրում','where do you live','vɔɾˈtɛʁ ɛs ɑpˈɾum'],
['որտեղ ես ծնվել','where was you born','vɔɾˈtɛʁ ɛs t͡sənˈvɛl'],
['որ','which','vɔɾ'],
['որ երկրի քաղաքացի եք','which country are you a citizen of','vɔɾ jɛɾˈkɾi kʰɑʁɑkʰɑˈt͡sʰi ɛkʰ'],
['թվական','year','tʰəvɑˈkɑn'],
['անգլիացի ես','you are English','ɑŋɡlijɑˈt͡sʰi ɛs'],
['ունես','you have','uˈnɛs'],
['անունդ','your name*','ɑˈnunətʰ'],
['ձեր անունն','your name','d͡zɛɾ ɑˈnunː'],
['ձեր ծննդավայրը','your place of birth','d͡zɛɾ t͡sənəndɑˈvɑjɾə'],
['ձեր ազգանունը','your surname','d͡zɛɾ ɑzɡɑˈnunə'],
['ԱՄՆ','USA','ɑmn'],
['այժմ որտեղ եք բնակվում','where do you live now','ˈɑjʒəm vɔɾˈtɛʁ ɛkʰ bənɑkˈvum'],
['բնակվել','to live','bənɑkˈvɛl'],
['երբ','when','jɛɾpʰ'],
['երբ ես ծնվել','when was you born','jɛɾpʰ ɛs t͡sənˈvɛl'],
['խնդրում եմ','please','χəntʰˈɾum ɛm'],
['ծնվել','to be born','ծնվել'],
['հագար ինը հարյուր','1900','hɑˈzɑɾ ˈinə hɑɾˈjuɾ'],
['հագար ինը հարյուր ութսունվեց','1986','hɑˈzɑɾ ˈinə hɑɾˈjuɾ utʰsunˈvɛt͡sʰ'],
['հագար ինը հարյուր ութսունվեց թվականի','1986 year','hɑˈzɑɾ ˈinə hɑɾˈjuɾ utʰsunˈvɛt͡sʰ tʰəvɑkɑˈni'],
['ութսունվեց','86','utʰsunˈvɛt͡sʰ']];
