var u=[
['ազատքեղ','parsley','azatkʰeʁ'],
['աղցան','salad*','aʁʦʰan'],
['ամառ','summer','amar'],
['ամեն','every','amen'],
['ամեն*','each','amen'],
['ամերիկայից','from America','ameɾikajiʦʰ'],
['այս','this','ajs'],
['այսինքն','i.e.','ajsinkʰᵊn'],
['այսինքն*','namely','ajsinkʰᵊn'],
['այստեղ','here','ajsteʁ'],
['այսքան','so (much)','ajskʰan'],
['այսօր','today','ajsoɾ'],
['այցելել','to visit','ajʦʰelel'],
['անուն','name','anun'],
['ապուխտ','cured meat','apuχt'],
['ապուր','soup','apuɾ'],
['առատություն','abundance','aratutʰjun'],
['ասել','to say','asel'],
['ասում է','says','asum‿e'],
['արմավ','date','aɾmav'],
['բադրիջան','eggplant','badɾiʒan'],
['բազուկ','beet','bazuk'],
['բալ','cherry (sour)','bal'],
['բանան','banana','banan'],
['բանջարեղեն','vegetables','banʒaɾeʁen'],
['բողկ','radish','boʁk'],
['բրինձ','rice','bᵊɾinʣ'],
['գազար','carrot','gazaɾ'],
['գաթա','Armenian sweet bread','gatʰa'],
['գալ','to come','gal'],
['գարեջուր','beer','gaɾeʣuɾ'],
['գեղեցիկ','beautiful','geʁeʦʰik'],
['գեղեցկություն','beauty','geʁeʦʰkutʰjun'],
['գինի','wine','gini'],
['գիտե՞ք','do you know?','gitekʰ?'],
['գիտենալ','to know','gitenal'],
['գույն','color','gujn'],
['դդմիկ','zucchini','dᵊtʰmik'],
['դդում','pumpkin','dᵊtʰum'],
['դեղձ','peach','deʁʦʰ'],
['ելակ','strawberry','jelak'],
['ենք','building','ʃenkʰ'],
['երշիկ','sausage','jeɾʃik'],
['երևանցի','native of Yerevan','jeɾevanʦʰi'],
['զբոսաշրջիկ','tourist','zbosaʃᵊɾʤik'],
['էլ','also','el'],
['էլ*','too','el'],
['ըմպելիք','beverages','əmpelikʰ'],
['թան','tan','tʰan'],
['թարխուն','tarragon','tʰaɾχun'],
['թարմ','fresh','tʰaɾm'],
['թե ինչու','as to why','tʰe inʧʰu'],
['թեյ','tea','tʰej'],
['թխվածք','cookies','tʰᵊχvaʦkʰ'],
['թուզ','fig','tʰuz'],
['ինչ','what','inʧʰ'],
['ինչու','why','inʧʰu'],
['ինչպիսի','what a…','inʧʰpisi'],
['լավաշ','Armenian flat bread','lavaʃ'],
['լատիներեն','Latin','latineɾen'],
['լիմոն','lemon','limon'],
['լոլիկ','tomato','lolik'],
['խաղող','grape(s)','χaʁoʁ'],
['խմորեղեն','baked goods','χᵊmoɾeʁen'],
['խնձոր','apple','χᵊnʣoɾ'],
['խորոված','barbecue','χoɾovaʦ'],
['ծաղկակաղամբ','cauliflower','ʦaʁkakaʁamb'],
['ծիրան','apricot','ʦiɾan'],
['կա','to exist','ka'],
['կաթ','milk','katʰ'],
['կաթնաշոռ','cottage cheese','katʰnaʃor'],
['կաղամբ','cabbage','kaʁamb'],
['կարագ','butter','kaɾakʰ'],
['կարկանդակ','cake','kaɾkandak'],
['կարտոֆիլ','potato','kaɾtofil'],
['կենտրոնական','central','kentɾonakan'],
['կեռաս','cherry (sweet)','keras'],
['կիտրոն','lemon*','kitɾon'],
['համեմ','coriander','hamem'],
['համով','tasty','hamov'],
['հայրենիք','fatherland','hajɾenikʰ'],
['հանքային ջուր','mineral water','hankʰajin juɾ'],
['հապա ․․․','what about…','hapa'],
['հասկանալ','understand','haskanal'],
['հասկանում եմ','I understand','haskanum‿em'],
['հավ','chicken','hav'],
['հաց','bread','haʦʰ'],
['հիանալի','wonderful','hianali'],
['հիմա','now','hima'],
['ձիթապտուղ','olive','ʣitʰapᵊtuʁ'],
['ձմերուկ','watermelon','ʣəmeɾuk'],
['ձու','egg','ʣu'],
['ձուկ','fish','ʣuk'],
['ձվածեղ','omelet','ʣᵊvaʦeʁ'],
['մածուն','yogurt','maʦun'],
['մաղադանոս','parsley*','maʁadanos'],
['մանավանդ','especially','manavand'],
['միս','meat','mis'],
['միրգ','fruit','miɾkʰ'],
['մրգահյութ','fruit juice','mᵊɾkʰahjutʰ'],
['մրգեր','fruits','miɾkʰeɾ'],
['նարինջ','orange','naɾinʒ'],
['նոր','new','noɾ'],
['նուռ','pomegranate','nur'],
['նրա','his','nᵊɾa'],
['նրան','him','nᵊɾan'],
['շաքար','sugar','ʃakʰaɾ'],
['շուկա','market','ʃuka'],
['որ','that','voɾ'],
['ուղեկցել','to accompany','uʁekʦʰel'],
['ունենալ','to have','unenal'],
['ուսանողուհի','female student','usanoʁuhi'],
['ուտելիք','food','utelikʰ'],
['պաղպաղակ','ice-cream','paʁpaʁak'],
['պանիր','cheese','paniɾ'],
['պղպեղ','pepper','pᵊʁpeʁ'],
['ռեհան','basil','rehan'],
['սալաթ','salad','salatʰ'],
['սալոր','plum','saloɾ'],
['սամիթ','dill','samitʰ'],
['սեխ','melon','seχ'],
['սերկևիլ','quince','seɾkevil'],
['սխտոր','garlic','sᵊχtoɾ'],
['սմբուկ','eggplant*','sᵊmbuk'],
['սոխ','onion','soχ'],
['սունկ','mushroom','sunk'],
['սուրճ','coffee','suɾʧ'],
['ստեպղին','carrot*','stepʁin'],
['վայր','place','vajɾ'],
['վարունգ','cucumber','vaɾung'],
['տանել','to take','tanel'],
['տանձ','pear','tanʣ'],
['տանում է','he/she is taking','tanum e'],
['տարի','year','taɾi'],
['տեսակ','variety','tesak'],
['տեսակ*','sort','tesak'],
['տիկին','madam','tikin'],
['տոլմա','tolma','tolma'],
['քանի','how many?','kʰani?'],
['օղի','vodka','oʁi'],
['օր','day','oɾ']];

var uu=[
['Անին հիվանդ է','Ani is sick'],
['աղը կփոխանցե՞ս','would you pass the salt?'],
['անշուշտ','of course'],
['անցնում էի փողոցով','I was crossing street'],
['արդեն գնում էինք','already about to leave'],
['բարի ախորժա՛կ','bon appetit!'],
['գինի կամ ուրիշ խմիչք','wine or any other drink'],
['գինի ունե՞նք','do we have wine?'],
['գինի չունենք','we don’t have wine,'],
['գնում էինք','about to leave'],
['եթե կարելի է','if possible'],
['երբ պատրաստում է','when prepared'],
['երբ քեզ տեսա','when I saw you'],
['երկու կտոր','two pieces'],
['թան կլցնե՞ս','pour me tan?'],
['թե ի՞նչ է','what it is?'],
['ժամը չորսին','at four o’clock'],
['ի՞նչ ենք խմում','what shall we drink?'],
['ի՞նչ է','what is it?'],
['իհարկե','of course*'],
['ինձ կբերե՞ս','would you bring me?'],
['ինձ մի բաժակ ջուր կբերե՞ս','would you bring me a glass of water?'],
['ինչո՞ւ եք հարցնում','why do you ask?'],
['խնդրեմ','please'],
['կարիր մատիտ ունե՞ս','do you have a red pencil?'],
['կարկանդակ չէ','it isn’t cake'],
['կարո՞ղ ես կռահել','can you guess?'],
['կենացդ','cheers'],
['համեցե՛ք','here you are!'],
['համով ճաշ է','delicious meal'],
['հայ են','they are Armenians*'],
['հայկական գարեջուրը','Armenian beer'],
['հաշվիչ','calculator'],
['հաց է՞լ ես ուզում','would you like some bread, too?'],
['ճաշերը համով են','meals are tasty'],
['մատիտ ունե՞ս','do you have a pencil?'],
['մի բաժակ ջուր','a glass of water'],
['մի բան եմ բերել','I brought something'],
['մի բան եմ խնդրելու','I have something to ask you'],
['մի րոպեով','for a moment'],
['մի րոպեով է ինձ պետք','I need it for a minute'],
['մի քիչ','some'],
['միշտ համով','always tasty'],
['մտածում եմ','I think'],
['մտածում եմ՝ ուրեմն կամ','I think, therefore I exist'],
['նա այստեղ է','he is here'],
['նա այստեղ է լինում','he is usually here'],
['նա ժամը չորսին այստեղ է լինում','at 4 o’clock, he is usually here'],
['նա քիչ էր ուտում','he used to eat a little'],
['նախկինում','in the past'],
['նրանք հայ են','they are Armenians'],
['շատ գրքեր կան','there are many books'],
['շատ էր աշխատում','work a lot'],
['շատ ծարավ եմ','I’m very thirsty'],
['շնորհակա՛լ եմ','thank you!'],
['ուրեմն կամ','therefore I exist'],
['ուրիշ խմիչք ունե՞նք','do we have other drink?'],
['չարժե','don’t mention it'],
['պաղպաղակ է','it’s ice-cream'],
['ջո՞ւր ես ուզում','do you want water?'],
['սա ձե՞ր հաշվիչն է','is this your calculator?'],
['սա ձեր հաշվիչն է','his is your calculator'],
['սառը գարեջուր','cold beer'],
['սառը ջուր','cold water'],
['սառն է','it’s cold'],
['սառույց չէ','it isn’t ice'],
['սառույցո՞վ','with ice?'],
['սեղանի վրա','on the table'],
['սեղանի վրա շատ գրքեր կան','there are many books on the table'],
['սիրով','gladly'],
['վերադարձրու','return it'],
['քաղցր է','it’s sweet'],
['քեզ էլ','the same to you'],
['քիչ էր քնում','sleep a little']];