var u=[
['Գերմանիա','Germany','ɡɛɾˈmɑnjɑ'],
['Թուրքիա','Turkey','ˈtʰuɾkʰjɑ'],
['Իտալիա','Italy','iˈtɑljɑ'],
['Լեհաստան','Poland','lɛhɑsˈtɑn'],
['Կանադա','Canada','kɑˈnɑdɑ'],
['Հայաստան','Armenia','hɑjɑsˈtɑn'],
['Հնդկաստան','India','həndkɑsˈtɑn'],
['Ճապոնիա','Japan','ʤ'],
['Պարսկաստան','Persia','pɑɾskɑsˈtɑn'],
['Ռուսաստան','Russia','rusɑsˈtɑn'],
['ազգանունդ','your surname',''],
['անել','to do','ɑˈnɛl'],
['անունս','my name',''],
['անպայման','definitely','ɑnpɑjˈmɑn'],
['անպայման*','unconditional','ɑnpɑjˈmɑn'],
['բարձր','high','ˈbɑɾʦʰəɾ'],
['գերմանացի','german male','ɡɛɾmɑnɑˈʦʰi'],
['գնալ','to go','ɡəˈnɑl'],
['գոնե','at least','ˈɡɔnɛ'],
['գոռալ','to scream','ɡɔˈrɑl'],
['գուցե','perhaps','ɡuˈʦʰɛ'],
['գրեթե','almost','ɡəɾɛˈtʰɛ'],
['գրքերդ','your books',''],
['եմ','I am now','ɛm'],
['երգել','to sing','jɛɾˈkʰɛl'],
['զանգահարել','to phone','zɑŋɡɑhɑˈɾɛl'],
['թուրքական','turkish','tʰuɾkʰɑˈkɑn'],
['իհարկե','of course','iˈhɑɾkɛ'],
['իննսուներորդ','ninetieth','inːsunɛˈɾɔɾd'],
['իտալական','italian','itɑlɑˈkɑn'],
['իտալացի','italian male','itɑlɑˈʦʰi'],
['իտալուհի','italian female','itɑluˈhi'],
['լեհ','pole male','lɛh'],
['լինում եմ','I usually am',''],
['խաղալ','to play','χɑˈʁɑl'],
['խմել','to drink','χəˈmɛl'],
['խոսել','to speak','χɔˈsɛl'],
['կանադացի','canadian male',''],
['կատու','cat','kɑˈtu'],
['կատուն','the cat',''],
['կարդալ','to read','kɑɾˈtʰɑl'],
['հազալ','to cough','hɑˈzɑl'],
['հայ','Armenian male','hɑj'],
['հայ*','Armenian person','hɑj'],
['հայգիտություն','armenology',''],
['հայեր','armenians','hɑˈjɛɾ'],
['հայերեն','Armenian language','hɑjɛˈɾɛn'],
['հայերենը','the Armenian language',''],
['հայերենից','from the Armenian language',''],
['հայերը','the Armenians',''],
['հայը','the Armenian',''],
['հայուհի','Armenian female','hɑjuˈhi'],
['հայպգիտութունը','the Armenology',''],
['հինգերորդ','fifth','ˈhiŋɡɛɾɔɾtʰ'],
['հնդիկ','indian male','hənˈdik'],
['հնդկուհի','indian female',''],
['հույն','greek person','hujn'],
['հունական','Greek language','hunɑˈkɑn'],
['հուսալ','to hope',''],
['ճապոնացի','japanese male','ʧɑpɔnɑˈʦʰi'],
['մայրս','my mother',''],
['մանավանդ','above all','mɑnɑˈvɑnd'],
['մանավանդ*','especially','mɑnɑˈvɑnd'],
['մեղր','honey','ˈmɛʁəɾ'],
['մի վարդ','a rose',''],
['մի տղա','a boy',''],
['մի տուն','a house',''],
['միթե','is it possible','ˈmitʰɛ'],
['միմիայն','only','mimˈjɑjn'],
['նույնպես','also','ˈnujnpɛs'],
['շուն','dog','ʃun'],
['շունը','the dog',''],
['որոտալ','to thunder','vɔɾɔˈtɑl'],
['որևէ','any','ˈvɔɾɛv&#603;'],
['ունեմ','I have now','uˈnɛm'],
['ունենում','I usually have',''],
['ուշանալ','to be late','uʃɑˈnɑl'],
['ուտել','to eat','uˈtɛl'],
['չինարեն','Chinese language','ʧʰinɑˈɾɛn'],
['չինացի','chinese male','ʧʰinɑˈʦʰi'],
['պարել','to dance','pɑˈɾɛl'],
['պարսիկ','persian male','pɑɾˈsik'],
['ռուս','russian','rus'],
['ռուս*','russian person','rus'],
['ռուսական','russian*','rusɑˈkɑn'],
['ռուսերեն','Russian language','rusɛˈɾɛn'],
['ստեղծել','to create','(ə)stɛχˈʦɛl'],
['վագր','tiger','ˈvɑɡəɾ'],
['քանիերորդ','which one in the series?',''],
['քսաներորդ','twentieth','kʰəˈsɑnɛɾɔɾtʰ']];

uu=[
['Երեվան մայրաքաղաք է','Yerevan is a capital'],
['Երկար լեզուն','long tongue'],
['Երկիրը պտտվում է','the earth rotates'],
['Քանի՞ լեզու','How many languages'],
['ամեն ինչ','everything'],
['այս ամառ','this summer'],
['այստեղ եմ','i am now here'],
['այստեղ լինում եմ','i am usually here'],
['անգլերե՞ն եք խոսում','do you speak English?'],
['անգլերեն չե՞ք խոսում','do you not speak English?'],
['աշխարհի շինողն է','the builder of world is'],
['աշխարհի քանդողը է','the destroyer of world is'],
['ավերում են','they destroy'],
['արդեն կարդում է','he is already reading'],
['արևի շուրջը','around the sun'],
['գալի՞ս ես','are you coming?'],
['գնում ենք','we are going'],
['գնում ենք Հայաստան','we are going to Armenia'],
['գնում եք','you leaving'],
['դուք հա՞յ եք','are you Armenian?'],
['ես գրում եմ','I am writing'],
['ես գրում եմ*','I write'],
['ես կարդում եմ','I am reading'],
['ես կարդում եմ*','I read'],
['ես սովորում','you study'],
['ժամանակ ունեմ','I now have time'],
['ժամանակ ունենում եմ','I usually have time'],
['ի՞նչ ես անում','what are you doing?'],
['լավ գինի','good wine'],
['լավ գինի է','It is a good wine'],
['լավ հասկանում եմ','understand you well'],
['լեզու գիտեք','languages you know'],
['խոսում եք','you speak'],
['կարդում եք','you read'],
['կարդում է','he is reading'],
['կարճացնում է կյանքը','shortens life'],
['հասկանում եմ','understand you'],
['ձեզ չեմ լսում','I do not hear you'],
['մեծ երկիր','great country'],
['մեր փողոց','our street'],
['մի վարդ','a rose'],
['մի՞թե','how is it possible'],
['մտնում են','they enter'],
['մտնում են քաղաք','they enter the city'],
['նամակ գրեցի','I wrote a letter'],
['նամակ եմ գրում','I am writing a letter'],
['նկարում է','he is painting'],
['նրանք հայ են','they are Armenians'],
['շինողն լեզուն է','the builder is the tongue'],
['շինողն ու քանդողը','builder and destroyer'],
['շունն ու կատուն','the dog and the cat'],
['չեմ լսում','I do not hear'],
['չէ՞','do not you?'],
['չինարեն ես սովորում','you study Chinese'],
['պտտվում է արևի շուրջը','rotates around the sun'],
['սովորում է','he is learning'],
['քանդողը լեզուն է','destroyer is the tongue'],
['քանի՞ տարեկան ես','how old are you?']];