var uu=[
['իսկ դուք ինչպես եք','and how are you?'],
['իսկ սա','and this'],
['իսկ այս տղան','and this boy'],
['իսկ դու','and you?'],
['իսկ դուք','and You?*'],
['դուք ամերիկացի եք','are you american?'],
['դուք ամերիկուհի եք','are you american woman?'],
['դու հայ ես','are you armenian?'],
['դուք հայ եք','are You armenian?*'],
['մի բան հարցնել','ask something'],
['ձեզ հարցնել','ask you'],
['ներս արի','come in'],
['ներս եկեք','come in (pl)'],
['մատիտ ունես','do you have a pencil?'],
['մատիտ ունեք','do You have a pencil?*'],
['կարևոր չէ','don’t mention it'],
['չարժե','don’t mention it*'],
['ներեցեք','excuse me (pl)'],
['ներիր','excuse me'],
['բարի երեկո','good evening'],
['բարի լույս','good morning'],
['բարի գիշեր','good night'],
['լույս բարի','good night*'],
['մնաս բարով','goodbye'],
['մնաք բարով','goodbye (pl)'],
['ուսանող է','he is a student'],
['ամերիկացի է','he is american'],
['ինչպես ես','how are you'],
['ինչպես եք','how are You*'],
['ես ել լավ եմ','i am also well'],
['ամերիկացի եմ','i am american'],
['ամերիկուհի եմ','i am american woman'],
['հայ եմ','i am armenian'],
['կանադացի եմ','i am canadian'],
['ես կանադուհի եմ','i am canadian female'],
['լավ եմ','i am fine'],
['ես հայ չեմ','i am not armenian'],
['ուրախ եմ','i am pleased'],
['շատ ուրախ եմ','i am very pleased'],
['լավ եմ*','i am well'],
['գմաք բարով','leave well (pl)'],
['գնաս բարով','leave well'],
['կարելի է','may i?'],
['ազգանունս','my last name'],
['անունս','my name'],
['Աննան ազգությամբ','nationality of Anna'],
['ոչինչ','no probem'],
['անշուշտ','of course'],
['խնդրեմ','please'],
['Սամվելն ել','Samuel also'],
['ցտեսություն','see you later'],
['նա ուսուցչուհի է','she is a teacher'],
['անգլուհի է','she is engish'],
['ֆրանսուհի է','she is french'],
['մի բան','something'],
['ներողություն','sorry'],
['գմաք բարով*','take care (pl)'],
['գնաս բարով*','take care'],
['շնորհակալ եմ','thank you'],
['շնորհակալություն','thanks'],
['այս տղան','this boy'],
['այս պարոնը','this gentleman'],
['այս աղջիկը','this girl'],
['սա գիրք է','this is a book'],
['սա տետր է','this is a notebook'],
['այս տիկինը','this lady'],
['սա ինչ է','what is this'],
['ձեր անունը ինչ է','what is your name?'],
['ազգությամբ ինչ է','what nationality is?'],
['անունդ ինչ է','what’s your name?'],
['ով է այս','who is this'],
['կտաս','would you give'],
['կտաք','would You give*'],
['բարով եկար','you are welcome'],
['բարով եկեք','you are welcome (pl)'],
['անունդ','your name'],
['ձեր անունը','Your name*']];