var uu=[
['լինել թե չլինել','to be or not to be'],
['տուն ու դպրոց','Home and school'],
['ամեն ինչ','everything'],
['ամեն օր','every day'],
['այնտեղ ուսանողներն են նստում','the students sit there'],
['այստեղ','here'],
['այստեղ ի՞նչ ես անում','what are you doing here?'],
['այստեղ ի՞նչ ես տեսնում','what do you see here'],
['այստեղ ո՞վ է նստում','who sits here?'],
['աշխատո՞ւմ ես','do you work?'],
['ապրես','good for you'],
['բնավ դժվար չէ','not difficult at all'],
['բոլոր տառերը','all the letters'],
['բոլորը դեռ չգիտեմ','I don’t know them all yet'],
['բոլորը չգիտեմ','I don’t know them all'],
['գալիս եմ','I am coming'],
['գալիս եմ*','I come'],
['գրասեղաններ և աթոռներ','desks and chairs'],
['գրատախտակ ու նկարներ','a blackboard and pictures'],
['գրել և կարդալ չգիտեմ','I don’t write or read it'],
['գրիչներ և ռետին','pens and eraser'],
['գրկեր ու տետրեր','books and notebooks'],
['գրում եմ','I am writing'],
['գրում եմ*','I write'],
['դաս ունե՞ք','do you have classes?'],
['դասագիրք ունենք','we have textbook'],
['դասարանը փոքր է','the classroom is small'],
['դժվար է','difficult'],
['դրանով','with it'],
['եթե կիսեմ','if I cut it in half'],
['երկար է','it’s long'],
['ի՞նչ կա','what’s'],
['ի՞նչ կա սեղանի վրա','what’s on the table'],
['ինչո՞ւ չէ','why not?'],
['իսկ այստե՞ղ','and over there'],
['լավ աշակերտուհի ես','you are a good pupil female'],
['խաղ ու պար է','child’s play'],
['կարո՞ղ ես գրել','can you write?'],
['կարողանում եմ','I am usually able'],
['հայ չէ','He is not an Armenian'],
['հայերեն գիտես','know Armenian'],
['հայերեն եմ սովորում','I’m studying Armenian'],
['հայերեն քերականությունը','Armenian grammar'],
['հայերենը են սիրում','I like Armenian'],
['հայերենը շատ են սիրում','I like Armenian very much'],
['հայկական այբուբենը','Armenian alphabet'],
['հասկանում եմ','I understand'],
['մեց է','it’s big'],
['մի ժամացույց','a clock'],
['մի սեղան','a table'],
['մի քիչ էլ խոսում եմ','I also speak a little'],
['շաբաթը երկու անգամ','twice a week'],
['շատ լավ դասագիրք','very good textbook'],
['շատ հայ ընկերներ ունես','you have many Armenian friends'],
['ո՞ւզում ես','do you want?'],
['ուսանողներ','students'],
['ուսուցիչը','the teacher'],
['ուրի՞շ','what else'],
['ուրիշ ի՞նչ կա','what else is there?'],
['չեմ գալիս','I do not come'],
['չեմ գալիս*','I am not coming'],
['չեմ կարողանում','I am usually not able'],
['չի գրում','He is not writing'],
['պատին ի՞նչ կա','what’s on the wall'],
['սա դասարան է','this is a classroom'],
['սա ի՞նչ է','what’s this'],
['սեղանի վրա','on the table'],
['սկսենք','let’s start'],
['փոքր չէ','it’s not small'],
['քեզ քննեմ','examine you']];

var u=[
['լավ','good','lɑv'],
['պատասխան','answer','pɑtɑsˈχɑn'],
['այս','this','ɑjs'],
['խումբ','group','χumb'],
['սովորել','to learn','sɔvɔˈɾɛl'],
['աշակերտ','pupil male','ɑʃɑˈkɛɾt'],
['աշակերտուհի','pupil female','ɑʃɑkɛɾtuˈhi'],
['արդեն','already','ɑɾˈtʰɛn'],
['մի քիչ','a little','mi kʰiʧʰ'],
['այսօր','today','ɑjˈsɔɾ'],
['էլ','too','ɛl'],
['էլ*','also','ɛl'],
['հաշվել','to count','hɑʃˈvɛl'],
['ուսուցչուհի','teacher female','usuʦʰʧʰuˈhi'],
['հարցնել','to ask','hɑɾʦʰˈnɛl'],
['եթե','if','jɛˈtʰɛ'],
['կավիճ','chalk','kɑˈviʧ'],
['կիսել','to cut in half','kiˈsɛl'],
['քանի՞','how many?','kʰɑˈni'],
['կտոր','piece','kəˈtɔɾ'],
['ունենալ','to have','unɛˈnɑl'],
['պատասխանել','to answer','pɑtɑsχɑˈnɛl'],
['նորից','again',''],
['ամեն','every','ɑˈmɛn'],
['ամեն*','each','ɑˈmɛn'],
['ասել','to say','ɑˈsɛl'],
['իսկ','and, but','isk'],
['փոշի','dust','pʰɔˈʃi'],
['մնալ','to remain','məˈnɑl'],
['մնալ*','to stay','məˈnɑl'],
['չի մնա','won’t remain',''],
['դառնալ','to become','dɑrˈnɑl'],
['դառնալ*','to turn','dɑrˈnɑl'],
['կդառնա','will become',''],
['կդառնա*','will turn into',''],
['սենյակ','room','sɛnˈjɑk'],
['կահույք','furniture','kɑˈhujkʰ'],
['բազկաթոռ','armchair','bɑzkɑˈtʰɔr'],
['պատշգամբ','balcony','pɑtəʃˈɡɑmb'],
['լողարան','bathroom','lɔʁɑˈɾɑn'],
['մահճակալ','bed (furniture)','mɑhʧɑˈkɑl'],
['անկողին','bed (mattress and bedding)','ɑŋkɔˈʁin'],
['ննջասենյակ','bedroom','nːʤɑsɛnˈjɑk'],
['գորգ','carpet','ɡɔɾɡ'],
['առաստաղ','ceiling','ɑrɑsˈtɑʁ'],
['աթոռ','chair','ɑˈtʰɔr'],
['ժամացույց','clock','ʒɑmɑˈʦʰujʦʰ'],
['միջանցք','corridor','miˈʧʰɑnʦʰkʰ'],
['միջանցք*','hallway','miˈʧʰɑnʦʰkʰ'],
['բազմոց','couch','bɑzˈmɔʦʰ'],
['վարագույր','curtain','vɑɾɑˈkʰujɾ'],
['ճաշասենյակ','dining room','ʧɑʃɑsɛnˈjɑk'],
['դուռ','door','dur'],
['մուտք','entrance','mutkʰ'],
['հատակ','floor','hɑˈtɑk'],
['տուն','house','tun'],
['տուն*','home','tun'],
['խոհանոց','kitchen','χɔhɑˈnɔʦʰ'],
['լուսամփոփ','lampshade','lusɑmˈpʰɔpʰ'],
['հյուրասենյակ','living room','hjuɾɑsɛnˈjɑk'],
['հայելի','mirror','hɑjɛˈli'],
['դաշնամուր','piano','dɑʃnɑˈmuɾ'],
['ռադիո','radio','rɑdˈjɔ'],
['աշխատասենյակ','study room','ɑʃχɑtɑsɛnˈjɑk'],
['սեղան','table','sɛˈʁɑn'],
['հեռախոս','telephone','hɛrɑˈχɔs'],
['հեռուստացույց','TV set','hɛrustɑˈʦʰujʦʰ'],
['զուգարան','toilet','zukʰɑˈɾɑn'],
['ծաղկաման','vase','ʦɑχkɑˈmɑn'],
['պատուհան','window','pɑtuˈhɑn'],
['դասարան','classroom','dɑsɑˈɾɑn'],
['լսարան','auditorium','lsɑˈɾɑn'],
['պայուսակ','bag','pɑjuˈsɑk'],
['նստարան','bench','nəstɑˈɾɑn'],
['գիրք','book','ɡiɾkʰ'],
['գրադարան','library','ɡəɾɑdɑˈɾɑn'],
['գրադարան*','bookcase','ɡəɾɑdɑˈɾɑn'],
['գրապահարան','bookcase*','ɡɾɑpɑhɑˈɾɑn'],
['գրատախտակ','blackboard','ɡəɾɑtɑχˈtɑk'],
['հաշվիչ','calculator','hɑʃˈviʧʰ'],
['համակարգիչ','computer','hɑmɑkɑɾˈkʰiʧʰ'],
['գրասեղան','desk','ɡəɾɑsɛˈʁɑn'],
['բառարան','dictionary','bɑrɑˈɾɑn'],
['ռետին','eraser','rɛˈtin'],
['քննություն','exam','kʰənːuˈʦʰjun'],
['թղթապանակ','file','tʰəχtʰɑpɑˈnɑk'],
['դասախոսություն','lecture','dɑsɑχɔsuˈʦʰjun'],
['դաս','lesson','dɑs'],
['քարտեզ','map','kʰɑɾˈtɛz'],
['նկար','picture','nəˈkɑɾ'],
['ցուցափայտ','pointer','ʦʰuʦʰɑˈpʰɑjt'],
['տետր','notebook','ˈtɛtəɾ'],
['գրասենյակ','office','ɡəɾɑsɛnˈjɑk'],
['էջ','page','ɛʤ'],
['թուղթ','paper','tʰuχtʰ'],
['գրիչ','pen','ɡəˈɾiʧʰ'],
['մատիտ','pencil','mɑˈtit'],
['գրչատուփ','pen tray','ɡəɾʧʰɑˈtupʰ'],
['բեմահարթակ','podium','bɛmɑhɑɾˈtʰɑk'],
['ամբիոն','pulpit','ɑmbiˈɔn'],
['քանոն','ruler','kʰɑˈnɔn'],
['դասագիրք','textbook','dɑsɑˈɡiɾkʰ'],
['գրել','to write','ɡəˈɾɛl'],
['չգրել','not to write',''],
['կարդալ','to read','kɑɾˈtʰɑl'],
['չկարդալ','not to read',''],
['լինել','to be','liˈnɛl'],
['չլինել','not to be',''],
['չունենալ','not to have',''],
['եմ','I am','ɛm'],
['չեմ','I am not',''],
['ունեմ','I have','uˈnɛm'],
['չունեմ','I do not have',''],
['գիտեմ','I know','ɡiˈtɛm'],
['չգիտեմ','I do not know','ʧʰəɡiˈtɛm'],
['գալ','to come','ɡɑl'],
['տալ','to give','tɑl'],
['լալ','to cry','lɑl'],
['կարող եմ','I can','']];