var u= [
['օգուտ','profit*','okʰut'],
['օգնել','to help*','okʰnel'],
['քսաներկու','twenty-two*','kʰsaneɾku'],
['քող','veil*','kʰoʁ'],
['քաղաք','city*','kʰaʁakʰ'],
['րոպե','minute*','ɾope'],
['տղա ես','you are a boy*','tᵊʁa‿jes'],
['վայրէջք','descent*','vajɾeʧʰkʰ'],
['պարգև','award*','paɾkʰev'],
['չէ','is not*','ʧʰe'],
['ուրագ','adze*','uɾakʰ'],
['շոգի','steam*','ʃokʰi'],
['շոգ','hot (weather)*','ʃokʰ'],
['միրգ','fruit*','miɾkʰ'],
['մեքենա','machine*','mekʰena'],
['մարգարիտ','pearl*','maɾkʰaɾit'],
['մարգարե','prophet*','maɾkʰaɾe'],
['ձիգ','long*','ʣikʰ'],
['ձիգ*','tight*','ʣikʰ'],
['ձագ','the young*','ʣakʰ'],
['ձագ*','the offspring*','ʣakʰ'],
['հոգևորական','clergyman*','hokʰevoɾakan'],
['հոգս','worry*','hokʰs'],
['հոգնակի','plural*','hokʰnaki'],
['հոգի','soul*','hokʰi'],
['հոգեկան','spiritual*','hokʰekan'],
['հոգեբան','psychologist*','hokʰeban'],
['հասցե','address*','hasʦʰe'],
['հագնել','to dress*','hakʰnel'],
['կող','rib*','koʁ'],
['կող*','flank*','koʁ'],
['կիսաեփ','half-cooked*','kisajepʰe'],
['կարգ','class*','kaɾkʰ'],
['կարգ*','row*','kaɾkʰ'],
['կարագ','butter*','kaɾakʰ'],
['կապիկ','monkey*','kapik'],
['իգական','female*','ikʰakan'],
['թեթև','light*','tʰetʰev'],
['թարգմանել','to translate*','tʰaɾkʰmanel'],
['թագավոր','king*','takʰavoɾ'],
['էջ','page*','eʤ'],
['էժան','cheap*','eʒan'],
['էակ','creature*','ejak'],
['եփել','to cook*','jepʰel'],
['երգել','to sing*','jeɾkʰel'],
['երգ','song*','jeɾkʰ'],
['երազ','dream*','jeɾaz'],
['ես','I*','jes'],
['ելք','exit*','jelkʰ'],
['եթե','if*','jetʰe'],
['գրել','to write*','gᵊɾel'],
['գուցե','perhaps*','guʦʰe'],
['գող','thief*','goʁ'],
['գնում եմ','I am going*','gᵊnum‿em'],
['գալու եմ','I will come*','galu‿jem'],
['գագաթ','summit*','gagatʰ'],
['բազե','falcon*','baze'],
['ասում են','they say*','asum‿en'],
['անէանալ','to disappear*','anejanal'],
['աներես','shameless*','aneɾes'],
['ամենաերկար','longest*','amenajeɾkaɾ'],
['Քրիստոս','Christ*','kʰɾistos'],
['Կատարինե','Catherine*','kataɾine'],
['Գագիկ','Gagik*','gagik'],
['Գաբրիել','Gabriel*','gabɾiel']];


