var u=[
['ազգասեր','patriot','azgasɛɾ'],
['ազգասերներ','patriots','azgasɛɾnɛɾ'],
['այբուբեն','alphabet','ajbubɛn'],
['առևտուր','commerce','arɛvtuɾ'],
['աստղ','star','astᵊʁ'],
['աստղեր','stars','astʁɛɾ'],
['բազմաթիվ','numerous','bazmatʰiv'],
['բոլոր','all','bɔlɔɾ'],
['գառ','lamb','gar'],
['գառներ','lambs','garnɛɾ'],
['գետափ','riverbank','gɛtapʰ'],
['գին','price','gin'],
['գինետուն','wine celar','ginɛtun'],
['գիրք','book','giɾkʰ'],
['գյուղացի','a peasant','gjuʁaʦʰi'],
['գյուղացիներ','peasants',''],
['գյուղացիք','peasants*',''],
['գնացուցակ','price list','gᵊnaʦʰuʦʰak'],
['գորգ','carpet','gɔɾg'],
['գորգեր','carpets','gɔɾgɛɾ'],
['գրասեղան','desk','gᵊɾasɛʁan'],
['դասագիրք','textbook','dasagiɾkʰ'],
['դասագիրքեր','textbooks','dasagiɾkʰɛɾ'],
['դուռ','door','dur'],
['դռներ','doors','dᵊrnɛɾ'],
['երևանցի','a native of Yerevan','jɛɾɛvanʦʰi'],
['երևանցիներ','natives of Yerevan',''],
['երևանցիք','natives of Yerevan*',''],
['զգեստ','dress','ᵊzgɛst'],
['զգեստներ','dresses','ᵊzgɛstnɛɾ'],
['թոռ','grandchild','tʰɔr'],
['թոռներ','grandchildren','tʰɔrnɛɾ'],
['ինքնաթիռ','airplane','inkʰnatʰir'],
['լեռ','mountain','lɛr'],
['լեռներ','mountains','lɛrnɛɾ'],
['լիալուսին','full moon','lialusin'],
['լոռեցի','a local from Lori','lɔrɛʦʰi'],
['լոռեցիներ','locals from Lori',''],
['լոռեցիք','locals from Lori*',''],
['լույս','light','lujs'],
['լույսեր','lights','lujsɛɾ'],
['լուսամփոփ','lampshade','lusampʰɔpʰ'],
['ծառ','tree','ʦar'],
['ծովափ','seashore','ʦɔvapʰ'],
['կանայք','women','kanajkʰ'],
['կեսօր','noon','kɛsɔɾ'],
['կեսօր*','midday','kɛsɔɾ'],
['կերուխում','feast','kɛɾuχum'],
['կին','woman','kin'],
['հարցազրույց','interview','haɾʦʰazᵊɾujʦʰ'],
['հյուրասենյակ','living room','hjuɾasɛnjak'],
['ձկնորս','fisherman','ʣᵊknɔɾs'],
['ձկնորսներ','fishermen','ʣᵊknɔɾsnɛɾ'],
['մատենագիր','bibliographer','matɛnagiɾ'],
['մատիտ','pencil','matit'],
['մատիտներ','pencils','matitnɛɾ'],
['մատյան','manuscript','matjan'],
['մարդ','man','maɾtʰ'],
['մարդ*','human being','maɾtʰ'],
['մարդասպան','murderer','maɾtʰaspan'],
['մարդիկ','human beings','maɾtʰik'],
['մարդիկ*','men','maɾtʰik'],
['մի քանի','a few','mi ‿ kʰani'],
['նավ','boat','nav'],
['նկար','picture','nᵊkaɾ'],
['նկարներ','pictures','nᵊkaɾnɛɾ'],
['շատ','many','ʃat'],
['շոգենավ','steamboat','ʃɔkʰɛnav'],
['շոգենավեր','steamboats','ʃɔkʰɛnavɛɾ'],
['որոշ','certain','ʋɔɾɔʃ'],
['պատուհան','window','patuhan'],
['պատուհաններ','windows','patuhannɛɾ'],
['պարոն','Sir','paɾɔn'],
['պարոն*','gentleman','paɾɔn'],
['պարոնայք','gentlemen','paɾɔnajkʰ'],
['պարոնայք*','Sirs','paɾɔnajkʰ'],
['ստախոս','liar','sᵊtaχɔs'],
['ստախոսներ','liars','sᵊtaχɔsnɛɾ'],
['վագր','tiger','vagᵊɾ'],
['վագրեր','tigers','vagɾɛɾ'],
['տիկին','Mrs','tikin'],
['տիկին*','madam','tikin'],
['տիկիններ','ladies','tikinnɛɾ'],
['տիկնայք','ladies*','tiknajkʰ'],
['տղամարդ','man*','tᵊʁamaɾtʰ'],
['տղամարդիկ','men*','tᵊʁamaɾtʰikʰ'],
['տոնածառ','Christmas tree','tɔnaʦar'],
['տոնածառեր','Christmas trees','tɔnaʦarɛɾɛɾ'],
['քանի՞','how many?','kʰani'],
['քիչ','few','kʰiʧʰ']];


var uu=[
['հինգ մարդ','5 men'],
['ութ որ','8 days'],
['քսան էջ','20 pages'],
['քանի՞ կտոր','how many pieces?'],
['չորս կտոր','four pieces'],
['բոլոր հարցերը','all (the) questions'],
['որոշ ուսանողներ','certain students'],
['բազմաթիվ գույներ','numerous colors'],
['շատ բան','many things'],
['շատ բաներ','many things'],
['քիչ մարդ','few people'],
['քիչ մարդիկ','few people*'],
['ժամանակ ունեմ','I have time'],
['դրամ չունե՞ս','don’t you have money?'],
['Արամը հայ է','Aram is an Armenian'],
['Ջոնը հայ չէ','John is not an Armenian'],
['խոսում ենք','we are talking'],
['չէք լսում','you are not listening'],
['ո՞ւր ես գնում','<em>where</em> are you going?'],
['տուն եմ գնում','I am going <em>home</em>'],
['ո՞վ չի հարցնում','<em>who</em> is not asking?'],
['Աննան չի հարցնում','<em>Anna</em> is not asking'],
['ո՞վ է գրում','<em>who</em> is writing?'],
['Ես եմ ցրում','<em>I</em> am writing'],
['ի՞նչ ես գրում','<em>what</em> are you writing?'],
['նամակ եմ գրում','I am writing a <em>letter</em>'],
['ո՞ւմ ես ցրում','<em>to whom</em> are you writing?'],
['քեզ եմ ցրում','I am writing <em>to you</em>'],
['ո՞վ է նամակ գրում','<em>who</em> is writing a letter?'],
['նա է նամակ գրում','<em>he</em> is writing a letter'],
['ո՞ւմ է նա նամակ գրում','<em>to whom</em> is he writing a letter?'],
['նա քեզ է նամակ գրում','he is writing a letter <em>to you</em>'],
['ե՞րբ է նա նամակ գրում','<em>when</em> is he writing a letter?'],
['նա այսօր ե նամակ գրում','he is writing a letter <em>today</em>']];

