var uu= [
['ձեր տունն','your house'],
['ավելի մեծ է','is bigger'],
['քան մերը','than ours'],
['բայց նրանցը փոքր է','but theirs is small'],
['նրանցը փոքր է','but theirs is small'],
['փոքր է','is small'],
['ձերոնք որտե՞ղ են','where are your folks?'],
['որտե՞ղ են','where are your?'],
['մերոնք','my folks'],
['մի շտ տանն են','always at home'],
['տանն են','at home'],
['իր ընկերոջը և նրա շանը','his friend and his dog'],
['հայերը հարգում են','Armenians respect'],
['հարգում են','respect'],
['հայերը հարգում են իրենց հյուրերին','Armenians respect their guests'],
['պատվում նրանց','honor them']];

var u=[
['իմ գիրքը','my book*','im giɾkʰə'],
['իմ տունը','my house','im tunə'],
['Հայաստան','Armenia','hajastan'],
['Հունաստան','Greece','hunastan'],
['Չինաստան','China','ʧʰinastan'],
['Ռուսաստան','Russia','rusastan'],
['Վրաստան','Georgia','vɾastan'],
['աղջիկ','girl',''],
['այբբենարան','primer','ajpbenaɾan'],
['աշակերտ','male pupil',''],
['աշակերտուհի','female pupil',''],
['աշխատանք','work','aʃχatankʰ'],
['աշխատել','to work','aʃχatel'],
['առատ','abundant','arat'],
['առատ*','plenty','arat'],
['առատություն','abundance','aratutʰjun'],
['ավետարան','bible','avetaɾan'],
['արսկաստան','Persia','paɾskastan'],
['արվեստ','art','aɾvest'],
['արվեստանոց','art studio','aɾvestanoʦʰ'],
['բառարան','dictionary','baraɾan'],
['բնակարան','apartment','bᵊnakaɾan'],
['գիրքդ','your book*','giɾkʰᵊt'],
['գիրքը','his book','giɾkʰə'],
['իրենց գիրքը','their book*','iɾenʦʰgiɾkʰə'],
['գիրքս','my book','giɾkʰᵊs'],
['գրքներդ','your book**','gᵊɾkʰneɾᵊt'],
['գրքները','their book**','gᵊɾkʰneɾə'],
['գրքներս','our book','gᵊɾkʰneɾᵊs'],
['դասարան','classroom','dasaɾan'],
['ընկեր','friend','ənkeɾ'],
['ընկերություն','friendship','ənkeɾutʰjun'],
['թշնամի','enemy','tʰᵊʃnami'],
['թշնամություն','enmity','tʰᵊʃnamutʰjun'],
['իմ','my','im'],
['իմը','mine','imə'],
['իր','his*','iɾ'],
['իր գիրքը','his book*','iɾ giɾkʰə'],
['իր շունը','his dog','iɾ ʃunə'],
['իր*','her','iɾ'],
['իր**','its','iɾ'],
['իրանց','their','iɾenʦʰ'],
['իրենը','his','iɾenə'],
['իրենը*','hers','iɾenə'],
['իրենը**','its*','iɾenə'],
['իրենցը','theirs','iɾenʦʰə'],
['իրենք','they*',''],
['լողարան','bathroom','loʁaɾan'],
['խաղաղ','peaceful','χaʁaʁ'],
['խաղաղություն','peace','χaʁaʁutʰjun'],
['ծանր','heavy','ʦanᵊɾ'],
['ծանրություն','weight','ʦanɾutʰjun'],
['ծեր','old','ʦeɾ'],
['ծերանոց','old age home','ʦeɾanoʦʰ'],
['հալածանք','persecution','halaʦankʰ'],
['հալածել','to persecute','halaʦel'],
['համալսարան','university','hamalsaɾan'],
['հայր','father',''],
['հարյուր','hundred','haɾjuɾ'],
['հարյուրանոց','a hundred-dram-bill','haɾjuɾanoʦʰ'],
['հինգ','five','hing'],
['հինգանոց','a five-dram-bill','hinganoʦʰ'],
['հիվանդ','sick','hivand'],
['հիվանդանոց','hospital','hivandanoʦʰ'],
['հյուր','guest','hjuɾ'],
['հյուրանոց','hotel','hjuɾanoʦʰ'],
['ձեր','your (pl)','ʣeɾ'],
['ձեր գիրքը','your (pl) book','ʣeɾ giɾkʰə'],
['ձերը','ours','ʣeɾə'],
['ձերը*','yours (pl)','ʣeɾə'],
['ձերոնք','your folks (pl)','ʣeɾonkʰ'],
['ճաշարան','restaurant','ʧaʃaɾan'],
['մայր','mother','majɾ'],
['մայրություն','motherhood','majɾutʰjun'],
['մարզանք','exercise','maɾzankʰ'],
['մարզանք*','gymnastics','maɾzankʰ'],
['մարզել','to train','maɾzel'],
['մարզել*','to drill','maɾzel'],
['մեծ','big','meʦ'],
['մեծ*','great','meʦ'],
['մեծություն','size','meʦutʰjun'],
['մեծություն*','greatness','meʦutʰjun'],
['մեր','our','meɾ'],
['մեր գիրքը','our book*','meɾ giɾkʰə'],
['մեր լեզուն','our language','meɾ lezun'],
['մեր տունը','our house',''],
['մերը','ours*','meɾə'],
['մերոնք','mine or ours folks','meɾonkʰ'],
['ներել','to forgive','neɾel'],
['ներում','forgiveness','neɾum'],
['նրա','his**','nᵊɾa'],
['նրա գիրքը','his book**','nᵊɾa giɾkʰə'],
['նրա շունը','his dog*','nᵊɾa ʃunə'],
['նրա տները','his houses',''],
['նրա*','her*','nᵊɾa'],
['նրա**','its**','nᵊɾa'],
['նրանը','his***','nᵊɾanə'],
['նրանը*','hers*','nᵊɾanə'],
['նրանը**','its***','nᵊɾanə'],
['նրանց','their*','nᵊɾanʦʰ'],
['նրանց գիրքը','their book','nᵊɾanʦʰ giɾkʰə'],
['նրանց երկիրը','their country','nᵊɾanʦʰ jeɾkiɾə'],
['նրանցը','theirs*','nᵊɾanʦʰə'],
['նրենք','they',''],
['շարժել','to move','ʃaɾʒel'],
['շարժում','movement','ʃaɾʒum'],
['շարունակել','to continue','ʃaɾunakel'],
['շարունակություն','continuation','ʃaɾunakutʰjun'],
['շունը','the dog','ʃunə'],
['շունը*','his dog**','ʃunə'],
['շունդ','your dog*','ʃunᵊt'],
['ուսանող','male student',''],
['ուսանողուհի','female student',''],
['ուրախ','happy','uɾaχ'],
['ուրախ*','joyful','uɾaχ'],
['ուրախություն','joy','uɾaχutʰjun'],
['պահարան','closet','pahaɾan'],
['պաշարել','to besiege','paʃaɾel'],
['պաշարում','siege','paʃaɾum'],
['պաշտպանել','to defend','paʃtpanel'],
['պաշտպանություն','defense','paʃtpanutʰjun'],
['պատդ','your wall','patᵊt'],
['պատը','his wall','patə'],
['պատներդ','your walls','patneɾᵊt'],
['պատներդ*','your wall*','patneɾᵊt'],
['պատները','their walls','patneɾə'],
['պատները*','his wall*','patneɾə'],
['պատներս','my walls','patneɾs'],
['պատներս*','our wall','patneɾs'],
['պատս','my wall','patᵊs'],
['սառնարան','refrigirator','sarnaɾan'],
['ստուգել','to check','stugel'],
['ստուգում','check-up','stugum'],
['վառարան','oven','varaɾan'],
['տանջանք','torture','tanjankʰ'],
['տանջանք*','suffering','tanjankʰ'],
['տանջել','to torture','tanjel'],
['տասանոց','a ten-dram-bill','tasanoʦʰ'],
['տասը','ten','tasə'],
['տղա','boy',''],
['տներդ','your houses','tᵊneɾᵊt'],
['տներդ*','your (pl) house','tᵊneɾᵊt'],
['տները','his house*','tᵊneɾə'],
['տները*','their houses','tᵊneɾə'],
['տներս','my houses','tᵊneɾs'],
['տներս*','our house*','tᵊneɾs'],
['տունդ','your house','tunᵊt'],
['տունը','his house**','tunə'],
['տունս','my house*','tunᵊs'],
['քննել','to examine','kᵊnːel'],
['քննություն','examination','kᵊnːutʰjun'],
['քո','your (inf)','kʰo'],
['քո գիրքը','your book','kʰo giɾkʰə'],
['քո կատուն','your cat','kʰo katun'],
['քո շունը','your dog','kʰo ʃunə'],
['քոնը','yours (inf)','kʰonə'],
['օգնել','to help','okʰnel'],
['օգնություն','help','okʰnutʰjun']];
